import 'general_data.dart';

final List<GeneralItem> electricityAndGadgets = [
  GeneralItem(
    name: 'Electric Bulb (बिजली का बल्ब)',
    category: 'Gadget',
    image: 'assets/general/electricity_gadgets/bulb.png',
    lives: '',
    eats: '',
    description: 'An electric bulb converts electrical energy into light.',
  ),
  GeneralItem(
    name: 'LED Bulb (एलईडी बल्ब)',
    category: 'Gadget',
    image: 'assets/general/electricity_gadgets/led_bulb.png',
    lives: '',
    eats: '',
    description: 'An LED bulb produces light using electricity and usually uses less energy than older bulbs.',
  ),
  GeneralItem(
    name: 'Tube Light (ट्यूब लाइट)',
    category: 'Gadget',
    image: 'assets/general/electricity_gadgets/tube_light.png',
    lives: '',
    eats: '',
    description: 'A tube light uses electricity to provide light over a larger area.',
  ),
  GeneralItem(
    name: 'Fan (पंखा)',
    category: 'Gadget',
    image: 'assets/general/electricity_gadgets/fan.png',
    lives: '',
    eats: '',
    description: 'An electric fan uses a motor to rotate its blades and move air.',
  ),
  GeneralItem(
    name: 'Ceiling Fan (सीलिंग फैन)',
    category: 'Gadget',
    image: 'assets/general/electricity_gadgets/ceiling_fan.png',
    lives: '',
    eats: '',
    description: 'A ceiling fan is fixed to the ceiling and moves air around a room.',
  ),
  GeneralItem(
    name: 'Table Fan (टेबल फैन)',
    category: 'Gadget',
    image: 'assets/general/electricity_gadgets/table_fan.png',
    lives: '',
    eats: '',
    description: 'A table fan is a portable electric fan used to move air.',
  ),
  GeneralItem(
    name: 'Air Conditioner (एयर कंडीशनर)',
    category: 'Gadget',
    image: 'assets/general/electricity_gadgets/air_conditioner.png',
    lives: '',
    eats: '',
    description: 'An air conditioner cools and helps control the temperature of indoor spaces.',
  ),
  GeneralItem(
    name: 'Refrigerator (रेफ्रिजरेटर)',
    category: 'Gadget',
    image: 'assets/general/electricity_gadgets/refrigerator.png',
    lives: '',
    eats: '',
    description: 'A refrigerator keeps food and drinks cool and helps them stay fresh for longer.',
  ),
  GeneralItem(
    name: 'Television (टेलीविजन)',
    category: 'Gadget',
    image: 'assets/general/electricity_gadgets/television.png',
    lives: '',
    eats: '',
    description: 'A television displays pictures and plays sound for entertainment and information.',
  ),
  GeneralItem(
    name: 'Radio (रेडियो)',
    category: 'Gadget',
    image: 'assets/general/electricity_gadgets/radio.png',
    lives: '',
    eats: '',
    description: 'A radio receives broadcasts and plays audio such as music and news.',
  ),
  GeneralItem(
    name: 'Computer (कंप्यूटर)',
    category: 'Gadget',
    image: 'assets/general/electricity_gadgets/computer.png',
    lives: '',
    eats: '',
    description: 'A computer processes information and can be used for learning, work, and entertainment.',
  ),
  GeneralItem(
    name: 'Laptop (लैपटॉप)',
    category: 'Gadget',
    image: 'assets/general/electricity_gadgets/laptop.png',
    lives: '',
    eats: '',
    description: 'A laptop is a portable computer used for studying, working, and many other tasks.',
  ),
  GeneralItem(
    name: 'Tablet (टैबलेट)',
    category: 'Gadget',
    image: 'assets/general/electricity_gadgets/tablet.png',
    lives: '',
    eats: '',
    description: 'A tablet is a portable touchscreen device used for learning, reading, games, and other activities.',
  ),
  GeneralItem(
    name: 'Mobile Phone (मोबाइल फोन)',
    category: 'Gadget',
    image: 'assets/general/electricity_gadgets/mobile_phone.png',
    lives: '',
    eats: '',
    description: 'A mobile phone allows people to communicate and use many digital services.',
  ),
  GeneralItem(
    name: 'Smartphone (स्मार्टफोन)',
    category: 'Gadget',
    image: 'assets/general/electricity_gadgets/smartphone.png',
    lives: '',
    eats: '',
    description: 'A smartphone combines communication, internet access, cameras, apps, and other functions.',
  ),
  GeneralItem(
    name: 'Smartwatch (स्मार्टवॉच)',
    category: 'Gadget',
    image: 'assets/general/electricity_gadgets/smartwatch.png',
    lives: '',
    eats: '',
    description: 'A smartwatch is a wearable electronic device that can show information and provide useful features.',
  ),
  GeneralItem(
    name: 'Calculator (कैलकुलेटर)',
    category: 'Gadget',
    image: 'assets/general/electricity_gadgets/calculator.png',
    lives: '',
    eats: '',
    description: 'A calculator performs mathematical calculations quickly.',
  ),
  GeneralItem(
    name: 'Digital Clock (डिजिटल घड़ी)',
    category: 'Gadget',
    image: 'assets/general/electricity_gadgets/digital_clock.png',
    lives: '',
    eats: '',
    description: 'A digital clock displays the time using numbers.',
  ),
  GeneralItem(
    name: 'Alarm Clock (अलार्म घड़ी)',
    category: 'Gadget',
    image: 'assets/general/electricity_gadgets/alarm_clock.png',
    lives: '',
    eats: '',
    description: 'An alarm clock shows the time and can make a sound at a set time.',
  ),
  GeneralItem(
    name: 'Electric Iron (इलेक्ट्रिक इस्त्री)',
    category: 'Gadget',
    image: 'assets/general/electricity_gadgets/iron.png',
    lives: '',
    eats: '',
    description: 'An electric iron uses heat to remove wrinkles from clothes.',
  ),
  GeneralItem(
    name: 'Washing Machine (वॉशिंग मशीन)',
    category: 'Gadget',
    image: 'assets/general/electricity_gadgets/washing_machine.png',
    lives: '',
    eats: '',
    description: 'A washing machine uses water, detergent, and mechanical movement to wash clothes.',
  ),
  GeneralItem(
    name: 'Microwave Oven (माइक्रोवेव ओवन)',
    category: 'Gadget',
    image: 'assets/general/electricity_gadgets/microwave.png',
    lives: '',
    eats: '',
    description: 'A microwave oven uses electromagnetic waves to heat food.',
  ),
  GeneralItem(
    name: 'Electric Oven (इलेक्ट्रिक ओवन)',
    category: 'Gadget',
    image: 'assets/general/electricity_gadgets/electric_oven.png',
    lives: '',
    eats: '',
    description: 'An electric oven uses electrical energy to produce heat for cooking and baking.',
  ),
  GeneralItem(
    name: 'Toaster (टोस्टर)',
    category: 'Gadget',
    image: 'assets/general/electricity_gadgets/toaster.png',
    lives: '',
    eats: '',
    description: 'A toaster uses electric heating elements to toast bread.',
  ),
  GeneralItem(
    name: 'Electric Kettle (इलेक्ट्रिक केतली)',
    category: 'Gadget',
    image: 'assets/general/electricity_gadgets/electric_kettle.png',
    lives: '',
    eats: '',
    description: 'An electric kettle uses electricity to heat and boil water.',
  ),
  GeneralItem(
    name: 'Mixer Grinder (मिक्सर ग्राइंडर)',
    category: 'Gadget',
    image: 'assets/general/electricity_gadgets/mixer_grinder.png',
    lives: '',
    eats: '',
    description: 'A mixer grinder uses a motor and rotating blades to mix or grind food.',
  ),
  GeneralItem(
    name: 'Juicer (जूसर)',
    category: 'Gadget',
    image: 'assets/general/electricity_gadgets/juicer.png',
    lives: '',
    eats: '',
    description: 'A juicer separates juice from fruits or vegetables.',
  ),
  GeneralItem(
    name: 'Electric Cooker (इलेक्ट्रिक कुकर)',
    category: 'Gadget',
    image: 'assets/general/electricity_gadgets/electric_cooker.png',
    lives: '',
    eats: '',
    description: 'An electric cooker uses electrical heat to cook food.',
  ),
  GeneralItem(
    name: 'Vacuum Cleaner (वैक्यूम क्लीनर)',
    category: 'Gadget',
    image: 'assets/general/electricity_gadgets/vacuum_cleaner.png',
    lives: '',
    eats: '',
    description: 'A vacuum cleaner uses suction to collect dust and dirt.',
  ),
  GeneralItem(
    name: 'Hair Dryer (हेयर ड्रायर)',
    category: 'Gadget',
    image: 'assets/general/electricity_gadgets/hair_dryer.png',
    lives: '',
    eats: '',
    description: 'A hair dryer uses warm air to help dry hair.',
  ),
  GeneralItem(
    name: 'Electric Shaver (इलेक्ट्रिक शेवर)',
    category: 'Gadget',
    image: 'assets/general/electricity_gadgets/electric_shaver.png',
    lives: '',
    eats: '',
    description: 'An electric shaver uses moving blades to trim or shave hair.',
  ),
  GeneralItem(
    name: 'Torch (टॉर्च)',
    category: 'Gadget',
    image: 'assets/general/electricity_gadgets/torch.png',
    lives: '',
    eats: '',
    description: 'A torch uses batteries to produce light and help us see in dark places.',
  ),
  GeneralItem(
    name: 'Battery (बैटरी)',
    category: 'Electrical Device',
    image: 'assets/general/electricity_gadgets/battery.png',
    lives: '',
    eats: '',
    description: 'A battery stores chemical energy and provides electrical energy to devices.',
  ),
  GeneralItem(
    name: 'Charger (चार्जर)',
    category: 'Electrical Device',
    image: 'assets/general/electricity_gadgets/charger.png',
    lives: '',
    eats: '',
    description: 'A charger supplies electrical energy to rechargeable batteries.',
  ),
  GeneralItem(
    name: 'Power Bank (पावर बैंक)',
    category: 'Gadget',
    image: 'assets/general/electricity_gadgets/power_bank.png',
    lives: '',
    eats: '',
    description: 'A power bank stores electrical energy and can charge portable devices.',
  ),
  GeneralItem(
    name: 'Plug (प्लग)',
    category: 'Electrical Device',
    image: 'assets/general/electricity_gadgets/plug.png',
    lives: '',
    eats: '',
    description: 'An electrical plug connects a device to a power supply.',
  ),
  GeneralItem(
    name: 'Socket (सॉकेट)',
    category: 'Electrical Device',
    image: 'assets/general/electricity_gadgets/socket.png',
    lives: '',
    eats: '',
    description: 'An electrical socket provides a connection point for a plug.',
  ),
  GeneralItem(
    name: 'Switch (स्विच)',
    category: 'Electrical Device',
    image: 'assets/general/electricity_gadgets/switch.png',
    lives: '',
    eats: '',
    description: 'A switch is used to open or close an electrical circuit.',
  ),
  GeneralItem(
    name: 'Wire (बिजली का तार)',
    category: 'Electrical Device',
    image: 'assets/general/electricity_gadgets/wire.png',
    lives: '',
    eats: '',
    description: 'An electrical wire provides a path for electric current to flow.',
  ),
  GeneralItem(
    name: 'Plug Board (प्लग बोर्ड)',
    category: 'Electrical Device',
    image: 'assets/general/electricity_gadgets/plug_board.png',
    lives: '',
    eats: '',
    description: 'A plug board provides several sockets for connecting electrical devices.',
  ),
  GeneralItem(
    name: 'Remote Control (रिमोट कंट्रोल)',
    category: 'Gadget',
    image: 'assets/general/electricity_gadgets/remote_control.png',
    lives: '',
    eats: '',
    description: 'A remote control allows us to operate devices from a distance.',
  ),
  GeneralItem(
    name: 'Speaker (स्पीकर)',
    category: 'Gadget',
    image: 'assets/general/electricity_gadgets/speaker.png',
    lives: '',
    eats: '',
    description: 'A speaker converts electrical signals into sound.',
  ),
  GeneralItem(
    name: 'Headphones (हेडफोन)',
    category: 'Gadget',
    image: 'assets/general/electricity_gadgets/headphones.png',
    lives: '',
    eats: '',
    description: 'Headphones allow a person to listen to audio privately.',
  ),
  GeneralItem(
    name: 'Earphones (ईयरफोन)',
    category: 'Gadget',
    image: 'assets/general/electricity_gadgets/earphones.png',
    lives: '',
    eats: '',
    description: 'Earphones are small audio devices worn in or near the ears.',
  ),
  GeneralItem(
    name: 'Camera (कैमरा)',
    category: 'Gadget',
    image: 'assets/general/electricity_gadgets/camera.png',
    lives: '',
    eats: '',
    description: 'A camera captures photographs and can also record videos.',
  ),
  GeneralItem(
    name: 'Projector (प्रोजेक्टर)',
    category: 'Gadget',
    image: 'assets/general/electricity_gadgets/projector.png',
    lives: '',
    eats: '',
    description: 'A projector displays images or videos onto a larger surface.',
  ),
  GeneralItem(
    name: 'Printer (प्रिंटर)',
    category: 'Gadget',
    image: 'assets/general/electricity_gadgets/printer.png',
    lives: '',
    eats: '',
    description: 'A printer produces text or images on paper.',
  ),
  GeneralItem(
    name: 'Wi-Fi Router (वाई-फाई राउटर)',
    category: 'Gadget',
    image: 'assets/general/electricity_gadgets/router.png',
    lives: '',
    eats: '',
    description: 'A Wi-Fi router connects devices to a network and can provide wireless internet access.',
  ),
  GeneralItem(
    name: 'Drone (ड्रोन)',
    category: 'Gadget',
    image: 'assets/general/electricity_gadgets/drone.png',
    lives: '',
    eats: '',
    description: 'A drone is an unmanned flying device that can be controlled remotely or programmed.',
  ),
  GeneralItem(
    name: 'Game Console (गेम कंसोल)',
    category: 'Gadget',
    image: 'assets/general/electricity_gadgets/game_console.png',
    lives: '',
    eats: '',
    description: 'A game console is an electronic device designed mainly for playing video games.',
  ),
  GeneralItem(
    name: 'Smart Speaker (स्मार्ट स्पीकर)',
    category: 'Gadget',
    image: 'assets/general/electricity_gadgets/smart_speaker.png',
    lives: '',
    eats: '',
    description: 'A smart speaker can play audio and perform certain tasks using voice commands.',
  ),
  GeneralItem(
    name: 'Electric Vehicle Charger (इलेक्ट्रिक वाहन चार्जर)',
    category: 'Electrical Device',
    image: 'assets/general/electricity_gadgets/ev_charger.png',
    lives: '',
    eats: '',
    description: 'An electric vehicle charger supplies electrical energy to recharge an electric vehicle battery.',
  ),
];