import 'general_data.dart';

final List<GeneralItem> foodAndDrinks = [
  GeneralItem(
    name: 'Rice (चावल)',
    category: 'Food',
    image: 'assets/general/food_drinks/rice.png',
    lives: '',
    eats: '',
    description: 'Rice is a common staple food and gives our body energy.',
  ),
  GeneralItem(
    name: 'Wheat (गेहूं)',
    category: 'Food',
    image: 'assets/general/food_drinks/wheat.png',
    lives: '',
    eats: '',
    description: 'Wheat is used to make foods such as roti, bread, and pasta.',
  ),
  GeneralItem(
    name: 'Roti (रोटी)',
    category: 'Food',
    image: 'assets/general/food_drinks/roti.png',
    lives: '',
    eats: '',
    description: 'Roti is a flatbread commonly made from wheat flour.',
  ),
  GeneralItem(
    name: 'Bread (ब्रेड)',
    category: 'Food',
    image: 'assets/general/food_drinks/bread.png',
    lives: '',
    eats: '',
    description: 'Bread is a common food made mainly from flour and water.',
  ),
  GeneralItem(
    name: 'Milk (दूध)',
    category: 'Drink',
    image: 'assets/general/food_drinks/milk.png',
    lives: '',
    eats: '',
    description: 'Milk provides nutrients such as calcium and protein.',
  ),
  GeneralItem(
    name: 'Curd (दही)',
    category: 'Food',
    image: 'assets/general/food_drinks/curd.png',
    lives: '',
    eats: '',
    description: 'Curd is a dairy food made by fermenting milk.',
  ),
  GeneralItem(
    name: 'Cheese (पनीर/चीज़)',
    category: 'Food',
    image: 'assets/general/food_drinks/cheese.png',
    lives: '',
    eats: '',
    description: 'Cheese is a dairy food that provides protein and calcium.',
  ),
  GeneralItem(
    name: 'Paneer (पनीर)',
    category: 'Food',
    image: 'assets/general/food_drinks/paneer.png',
    lives: '',
    eats: '',
    description: 'Paneer is a fresh cheese commonly used in Indian dishes.',
  ),
  GeneralItem(
    name: 'Butter (मक्खन)',
    category: 'Food',
    image: 'assets/general/food_drinks/butter.png',
    lives: '',
    eats: '',
    description: 'Butter is made from milk fat and is commonly used in cooking and baking.',
  ),
  GeneralItem(
    name: 'Dal (दाल)',
    category: 'Food',
    image: 'assets/general/food_drinks/dal.png',
    lives: '',
    eats: '',
    description: 'Dal is made from pulses and is a good source of protein.',
  ),
  GeneralItem(
    name: 'Lentils (मसूर दाल)',
    category: 'Food',
    image: 'assets/general/food_drinks/lentils.png',
    lives: '',
    eats: '',
    description: 'Lentils are small pulses that provide protein, fibre, and other nutrients.',
  ),
  GeneralItem(
    name: 'Chickpeas (चना)',
    category: 'Food',
    image: 'assets/general/food_drinks/chickpeas.png',
    lives: '',
    eats: '',
    description: 'Chickpeas are nutritious pulses that provide protein and fibre.',
  ),
  GeneralItem(
    name: 'Peanuts (मूंगफली)',
    category: 'Food',
    image: 'assets/general/food_drinks/peanuts.png',
    lives: '',
    eats: '',
    description: 'Peanuts are seeds rich in protein and healthy fats.',
  ),
  GeneralItem(
    name: 'Almonds (बादाम)',
    category: 'Food',
    image: 'assets/general/food_drinks/almonds.png',
    lives: '',
    eats: '',
    description: 'Almonds are nutritious nuts containing protein, fibre, and healthy fats.',
  ),
  GeneralItem(
    name: 'Cashews (काजू)',
    category: 'Food',
    image: 'assets/general/food_drinks/cashews.png',
    lives: '',
    eats: '',
    description: 'Cashews are edible nuts with a creamy taste.',
  ),
  GeneralItem(
    name: 'Walnuts (अखरोट)',
    category: 'Food',
    image: 'assets/general/food_drinks/walnuts.png',
    lives: '',
    eats: '',
    description: 'Walnuts are nutritious nuts containing healthy fats.',
  ),
  GeneralItem(
    name: 'Egg (अंडा)',
    category: 'Food',
    image: 'assets/general/food_drinks/egg.png',
    lives: '',
    eats: '',
    description: 'Eggs are a good source of protein and several nutrients.',
  ),
  GeneralItem(
    name: 'Chicken (चिकन)',
    category: 'Food',
    image: 'assets/general/food_drinks/chicken.png',
    lives: '',
    eats: '',
    description: 'Chicken is a protein-rich food made from poultry meat.',
  ),
  GeneralItem(
    name: 'Fish (मछली)',
    category: 'Food',
    image: 'assets/general/food_drinks/fish.png',
    lives: '',
    eats: '',
    description: 'Fish provides protein and several important nutrients.',
  ),
  GeneralItem(
    name: 'Apple (सेब)',
    category: 'Food',
    image: 'assets/general/food_drinks/apple.png',
    lives: '',
    eats: '',
    description: 'Apples are fruits that provide fibre and several vitamins.',
  ),
  GeneralItem(
    name: 'Banana (केला)',
    category: 'Food',
    image: 'assets/general/food_drinks/banana.png',
    lives: '',
    eats: '',
    description: 'Bananas are naturally sweet fruits that provide energy and potassium.',
  ),
  GeneralItem(
    name: 'Mango (आम)',
    category: 'Food',
    image: 'assets/general/food_drinks/mango.png',
    lives: '',
    eats: '',
    description: 'Mangoes are sweet tropical fruits enjoyed in many forms.',
  ),
  GeneralItem(
    name: 'Orange (संतरा)',
    category: 'Food',
    image: 'assets/general/food_drinks/orange.png',
    lives: '',
    eats: '',
    description: 'Oranges are juicy citrus fruits and a good source of vitamin C.',
  ),
  GeneralItem(
    name: 'Watermelon (तरबूज)',
    category: 'Food',
    image: 'assets/general/food_drinks/watermelon.png',
    lives: '',
    eats: '',
    description: 'Watermelon contains a lot of water and is refreshing in hot weather.',
  ),
  GeneralItem(
    name: 'Carrot (गाजर)',
    category: 'Food',
    image: 'assets/general/food_drinks/carrot.png',
    lives: '',
    eats: '',
    description: 'Carrots are vegetables rich in beta-carotene and fibre.',
  ),
  GeneralItem(
    name: 'Potato (आलू)',
    category: 'Food',
    image: 'assets/general/food_drinks/potato.png',
    lives: '',
    eats: '',
    description: 'Potatoes are starchy vegetables that provide energy.',
  ),
  GeneralItem(
    name: 'Tomato (टमाटर)',
    category: 'Food',
    image: 'assets/general/food_drinks/tomato.png',
    lives: '',
    eats: '',
    description: 'Tomatoes are commonly used in salads, curries, sauces, and other dishes.',
  ),
  GeneralItem(
    name: 'Spinach (पालक)',
    category: 'Food',
    image: 'assets/general/food_drinks/spinach.png',
    lives: '',
    eats: '',
    description: 'Spinach is a leafy green vegetable containing vitamins and minerals.',
  ),
  GeneralItem(
    name: 'Corn (मक्का)',
    category: 'Food',
    image: 'assets/general/food_drinks/corn.png',
    lives: '',
    eats: '',
    description: 'Corn is a grain that can be eaten in many different ways.',
  ),
  GeneralItem(
    name: 'Peas (मटर)',
    category: 'Food',
    image: 'assets/general/food_drinks/peas.png',
    lives: '',
    eats: '',
    description: 'Peas are small green seeds that provide protein and fibre.',
  ),
  GeneralItem(
    name: 'Soup (सूप)',
    category: 'Food',
    image: 'assets/general/food_drinks/soup.png',
    lives: '',
    eats: '',
    description: 'Soup is a liquid food made using vegetables, pulses, meat, or other ingredients.',
  ),
  GeneralItem(
    name: 'Salad (सलाद)',
    category: 'Food',
    image: 'assets/general/food_drinks/salad.png',
    lives: '',
    eats: '',
    description: 'Salad is commonly made using fresh vegetables, fruits, or other ingredients.',
  ),
  GeneralItem(
    name: 'Sandwich (सैंडविच)',
    category: 'Food',
    image: 'assets/general/food_drinks/sandwich.png',
    lives: '',
    eats: '',
    description: 'A sandwich is made by placing fillings between slices of bread.',
  ),
  GeneralItem(
    name: 'Pizza (पिज़्ज़ा)',
    category: 'Food',
    image: 'assets/general/food_drinks/pizza.png',
    lives: '',
    eats: '',
    description: 'Pizza is a baked food made with a flat dough base and different toppings.',
  ),
  GeneralItem(
    name: 'Idli (इडली)',
    category: 'Food',
    image: 'assets/general/food_drinks/idli.png',
    lives: '',
    eats: '',
    description: 'Idli is a soft steamed food commonly made from fermented rice and lentil batter.',
  ),
  GeneralItem(
    name: 'Dosa (डोसा)',
    category: 'Food',
    image: 'assets/general/food_drinks/dosa.png',
    lives: '',
    eats: '',
    description: 'Dosa is a thin South Indian dish usually made from fermented rice and lentil batter.',
  ),
  GeneralItem(
    name: 'Poha (पोहा)',
    category: 'Food',
    image: 'assets/general/food_drinks/poha.png',
    lives: '',
    eats: '',
    description: 'Poha is a popular Indian breakfast made from flattened rice.',
  ),
  GeneralItem(
    name: 'Upma (उपमा)',
    category: 'Food',
    image: 'assets/general/food_drinks/upma.png',
    lives: '',
    eats: '',
    description: 'Upma is a popular breakfast dish usually made from semolina.',
  ),
  GeneralItem(
    name: 'Khichdi (खिचड़ी)',
    category: 'Food',
    image: 'assets/general/food_drinks/khichdi.png',
    lives: '',
    eats: '',
    description: 'Khichdi is a simple dish commonly prepared using rice and pulses.',
  ),
  GeneralItem(
    name: 'Juice (फलों का रस)',
    category: 'Drink',
    image: 'assets/general/food_drinks/juice.png',
    lives: '',
    eats: '',
    description: 'Fruit juice is a drink made from the liquid of fruits.',
  ),
  GeneralItem(
    name: 'Water (पानी)',
    category: 'Drink',
    image: 'assets/general/food_drinks/water.png',
    lives: '',
    eats: '',
    description: 'Water is essential for life and helps our body perform many important functions.',
  ),
  GeneralItem(
    name: 'Lemon Water (नींबू पानी)',
    category: 'Drink',
    image: 'assets/general/food_drinks/lemon_water.png',
    lives: '',
    eats: '',
    description: 'Lemon water is made by mixing lemon juice with water.',
  ),
  GeneralItem(
    name: 'Coconut Water (नारियल पानी)',
    category: 'Drink',
    image: 'assets/general/food_drinks/coconut_water.png',
    lives: '',
    eats: '',
    description: 'Coconut water is the clear liquid naturally found inside coconuts.',
  ),
  GeneralItem(
    name: 'Tea (चाय)',
    category: 'Drink',
    image: 'assets/general/food_drinks/tea.png',
    lives: '',
    eats: '',
    description: 'Tea is a drink commonly prepared by steeping tea leaves in hot water.',
  ),
  GeneralItem(
    name: 'Hot Chocolate (हॉट चॉकलेट)',
    category: 'Drink',
    image: 'assets/general/food_drinks/hot_chocolate.png',
    lives: '',
    eats: '',
    description: 'Hot chocolate is a warm drink usually made with milk and cocoa.',
  ),
  GeneralItem(
    name: 'Lassi (लस्सी)',
    category: 'Drink',
    image: 'assets/general/food_drinks/lassi.png',
    lives: '',
    eats: '',
    description: 'Lassi is a traditional drink made mainly from curd and water or milk.',
  ),
  GeneralItem(
    name: 'Buttermilk (छाछ)',
    category: 'Drink',
    image: 'assets/general/food_drinks/buttermilk.png',
    lives: '',
    eats: '',
    description: 'Buttermilk is a light dairy drink commonly enjoyed in India.',
  ),
  GeneralItem(
    name: 'Smoothie (स्मूदी)',
    category: 'Drink',
    image: 'assets/general/food_drinks/smoothie.png',
    lives: '',
    eats: '',
    description: 'A smoothie is a thick drink made by blending fruits, vegetables, or other ingredients.',
  ),
  GeneralItem(
    name: 'Milkshake (मिल्कशेक)',
    category: 'Drink',
    image: 'assets/general/food_drinks/milkshake.png',
    lives: '',
    eats: '',
    description: 'A milkshake is a cold drink usually made with milk and blended ingredients.',
  ),
];