import 'general_data.dart';

final List<GeneralItem> fruits = [
  GeneralItem(
    name: 'Apple (सेब)',
    category: 'Fruit',
    image: 'assets/general/fruits/apple.png',
    lives: 'Grows on trees in cool and temperate regions',
    eats: 'People and animals',
    description: 'Apples are crunchy fruits that can be red, green, or yellow.',
  ),
  GeneralItem(
    name: 'Banana (केला)',
    category: 'Fruit',
    image: 'assets/general/fruits/banana.png',
    lives: 'Grows on banana plants in warm regions',
    eats: 'People and animals',
    description: 'Bananas are soft, sweet fruits rich in energy.',
  ),
  GeneralItem(
    name: 'Mango (आम)',
    category: 'Fruit',
    image: 'assets/general/fruits/mango.png',
    lives: 'Grows on mango trees in warm regions',
    eats: 'People and animals',
    description: 'Mango is a sweet and juicy fruit often called the king of fruits.',
  ),
  GeneralItem(
    name: 'Orange (संतरा)',
    category: 'Fruit',
    image: 'assets/general/fruits/orange.png',
    lives: 'Grows on citrus trees',
    eats: 'People and animals',
    description: 'Oranges are juicy citrus fruits rich in vitamin C.',
  ),
  GeneralItem(
    name: 'Grapes (अंगूर)',
    category: 'Fruit',
    image: 'assets/general/fruits/grapes.png',
    lives: 'Grows in bunches on grapevines',
    eats: 'People and animals',
    description: 'Grapes are small, juicy fruits that can be green, red, or purple.',
  ),
  GeneralItem(
    name: 'Watermelon (तरबूज)',
    category: 'Fruit',
    image: 'assets/general/fruits/watermelon.png',
    lives: 'Grows on vines on the ground',
    eats: 'People and animals',
    description: 'Watermelon is a large, juicy fruit that is especially refreshing in summer.',
  ),
  GeneralItem(
    name: 'Papaya (पपीता)',
    category: 'Fruit',
    image: 'assets/general/fruits/papaya.png',
    lives: 'Grows on papaya plants in warm climates',
    eats: 'People and animals',
    description: 'Papaya is a soft orange fruit with many black seeds.',
  ),
  GeneralItem(
    name: 'Guava (अमरूद)',
    category: 'Fruit',
    image: 'assets/general/fruits/guava.png',
    lives: 'Grows on small trees in warm climates',
    eats: 'People and animals',
    description: 'Guava is a fragrant fruit that can have white or pink flesh.',
  ),
  GeneralItem(
    name: 'Pineapple (अनानास)',
    category: 'Fruit',
    image: 'assets/general/fruits/pineapple.png',
    lives: 'Grows close to the ground',
    eats: 'People and animals',
    description: 'Pineapple has a rough outside and sweet, juicy flesh inside.',
  ),
  GeneralItem(
    name: 'Pomegranate (अनार)',
    category: 'Fruit',
    image: 'assets/general/fruits/pomegranate.png',
    lives: 'Grows on shrubs or small trees',
    eats: 'People and animals',
    description: 'Pomegranates contain many juicy red seeds called arils.',
  ),
  GeneralItem(
    name: 'Papaya (पपीता)',
    category: 'Fruit',
    image: 'assets/general/fruits/papaya.png',
    lives: 'Grows on papaya plants',
    eats: 'People and animals',
    description: 'Papaya is commonly eaten ripe and is also used in cooking when unripe.',
  ),
  GeneralItem(
    name: 'Pear (नाशपाती)',
    category: 'Fruit',
    image: 'assets/general/fruits/pear.png',
    lives: 'Grows on pear trees',
    eats: 'People and animals',
    description: 'Pears are sweet fruits with a soft, juicy texture.',
  ),
  GeneralItem(
    name: 'Peach (आड़ू)',
    category: 'Fruit',
    image: 'assets/general/fruits/peach.png',
    lives: 'Grows on peach trees',
    eats: 'People and animals',
    description: 'Peaches are soft fruits with juicy flesh and a large seed.',
  ),
  GeneralItem(
    name: 'Plum (आलूबुखारा)',
    category: 'Fruit',
    image: 'assets/general/fruits/plum.png',
    lives: 'Grows on plum trees',
    eats: 'People and animals',
    description: 'Plums are small fruits that can have purple, red, or yellow skin.',
  ),
  GeneralItem(
    name: 'Cherry (चेरी)',
    category: 'Fruit',
    image: 'assets/general/fruits/cherry.png',
    lives: 'Grows on cherry trees',
    eats: 'People and animals',
    description: 'Cherries are small, round fruits usually red or dark purple.',
  ),
  GeneralItem(
    name: 'Strawberry (स्ट्रॉबेरी)',
    category: 'Fruit',
    image: 'assets/general/fruits/strawberry.png',
    lives: 'Grows on small plants close to the ground',
    eats: 'People and animals',
    description: 'Strawberries are red fruits covered with tiny seeds.',
  ),
  GeneralItem(
    name: 'Blueberry (ब्लूबेरी)',
    category: 'Fruit',
    image: 'assets/general/fruits/blueberry.png',
    lives: 'Grows on small bushes',
    eats: 'People and animals',
    description: 'Blueberries are small blue-purple berries with a sweet taste.',
  ),
  GeneralItem(
    name: 'Raspberry (रास्पबेरी)',
    category: 'Fruit',
    image: 'assets/general/fruits/raspberry.png',
    lives: 'Grows on raspberry bushes',
    eats: 'People and animals',
    description: 'Raspberries are soft red berries made of many small sections.',
  ),
  GeneralItem(
    name: 'Blackberry (ब्लैकबेरी)',
    category: 'Fruit',
    image: 'assets/general/fruits/blackberry.png',
    lives: 'Grows on thorny bushes',
    eats: 'People and animals',
    description: 'Blackberries are dark-colored berries with a sweet and slightly sour taste.',
  ),
  GeneralItem(
    name: 'Kiwi (कीवी)',
    category: 'Fruit',
    image: 'assets/general/fruits/kiwi.png',
    lives: 'Grows on climbing vines',
    eats: 'People and animals',
    description: 'Kiwi has brown fuzzy skin and bright green flesh with tiny black seeds.',
  ),
  GeneralItem(
    name: 'Papaya (पपीता)',
    category: 'Fruit',
    image: 'assets/general/fruits/papaya.png',
    lives: 'Grows in tropical regions',
    eats: 'People and animals',
    description: 'Ripe papaya has soft orange flesh and many black seeds.',
  ),
  GeneralItem(
    name: 'Coconut (नारियल)',
    category: 'Fruit',
    image: 'assets/general/fruits/coconut.png',
    lives: 'Grows on coconut palm trees',
    eats: 'People and animals',
    description: 'Coconuts have a hard shell and contain refreshing coconut water and white flesh.',
  ),
  GeneralItem(
    name: 'Lemon (नींबू)',
    category: 'Fruit',
    image: 'assets/general/fruits/lemon.png',
    lives: 'Grows on citrus trees',
    eats: 'People and animals',
    description: 'Lemons are yellow citrus fruits with a strong sour taste.',
  ),
  GeneralItem(
    name: 'Lime (नींबू)',
    category: 'Fruit',
    image: 'assets/general/fruits/lime.png',
    lives: 'Grows on small citrus trees',
    eats: 'People and animals',
    description: 'Limes are small green citrus fruits with a sour taste.',
  ),
  GeneralItem(
    name: 'Mosambi (मौसंबी)',
    category: 'Fruit',
    image: 'assets/general/fruits/mosambi.png',
    lives: 'Grows on citrus trees',
    eats: 'People and animals',
    description: 'Mosambi is a sweet citrus fruit commonly enjoyed as fresh juice.',
  ),
  GeneralItem(
    name: 'Lychee (लीची)',
    category: 'Fruit',
    image: 'assets/general/fruits/lychee.png',
    lives: 'Grows in bunches on lychee trees',
    eats: 'People and animals',
    description: 'Lychee has rough red skin and sweet, juicy white flesh.',
  ),
  GeneralItem(
    name: 'Jackfruit (कटहल)',
    category: 'Fruit',
    image: 'assets/general/fruits/jackfruit.png',
    lives: 'Grows directly on the trunk and branches of trees',
    eats: 'People and animals',
    description: 'Jackfruit is a very large fruit with sweet yellow flesh inside.',
  ),
  GeneralItem(
    name: 'Dragon Fruit (ड्रैगन फ्रूट)',
    category: 'Fruit',
    image: 'assets/general/fruits/dragon_fruit.png',
    lives: 'Grows on climbing cactus plants',
    eats: 'People and animals',
    description: 'Dragon fruit has bright skin and soft flesh filled with tiny black seeds.',
  ),
  GeneralItem(
    name: 'Custard Apple (सीताफल)',
    category: 'Fruit',
    image: 'assets/general/fruits/custard_apple.png',
    lives: 'Grows on small trees',
    eats: 'People and animals',
    description: 'Custard apple has creamy, sweet flesh and many black seeds.',
  ),
  GeneralItem(
    name: 'Sapodilla (चीकू)',
    category: 'Fruit',
    image: 'assets/general/fruits/sapodilla.png',
    lives: 'Grows on evergreen trees',
    eats: 'People and animals',
    description: 'Sapodilla, also called chikoo, is a soft brown fruit with sweet flesh.',
  ),
  GeneralItem(
    name: 'Fig (अंजीर)',
    category: 'Fruit',
    image: 'assets/general/fruits/fig.png',
    lives: 'Grows on fig trees',
    eats: 'People and animals',
    description: 'Figs are soft fruits with many tiny edible seeds.',
  ),
  GeneralItem(
    name: 'Dates (खजूर)',
    category: 'Fruit',
    image: 'assets/general/fruits/dates.png',
    lives: 'Grows in clusters on date palm trees',
    eats: 'People and animals',
    description: 'Dates are naturally sweet fruits that are often dried and eaten.',
  ),
  GeneralItem(
    name: 'Avocado (एवोकाडो)',
    category: 'Fruit',
    image: 'assets/general/fruits/avocado.png',
    lives: 'Grows on avocado trees',
    eats: 'People and animals',
    description: 'Avocado has green flesh and one large seed in the center.',
  ),
  GeneralItem(
    name: 'Passion Fruit (पैशन फ्रूट)',
    category: 'Fruit',
    image: 'assets/general/fruits/passion_fruit.png',
    lives: 'Grows on climbing vines',
    eats: 'People and animals',
    description: 'Passion fruit has juicy pulp with many crunchy seeds.',
  ),
  GeneralItem(
    name: 'Star Fruit (कमरख)',
    category: 'Fruit',
    image: 'assets/general/fruits/star_fruit.png',
    lives: 'Grows on small tropical trees',
    eats: 'People and animals',
    description: 'When sliced, star fruit looks like a five-pointed star.',
  ),
  GeneralItem(
    name: 'Tamarind (इमली)',
    category: 'Fruit',
    image: 'assets/general/fruits/tamarind.png',
    lives: 'Grows in pods on tamarind trees',
    eats: 'People and animals',
    description: 'Tamarind has brown pods containing sour and sticky pulp.',
  ),
  GeneralItem(
    name: 'Amla (आंवला)',
    category: 'Fruit',
    image: 'assets/general/fruits/amla.png',
    lives: 'Grows on small amla trees',
    eats: 'People and animals',
    description: 'Amla is a small green fruit with a strong sour and slightly bitter taste.',
  ),
  GeneralItem(
    name: 'Mulberry (शहतूत)',
    category: 'Fruit',
    image: 'assets/general/fruits/mulberry.png',
    lives: 'Grows on mulberry trees',
    eats: 'People and animals',
    description: 'Mulberries are small berries that can be red, purple, or black.',
  ),
  GeneralItem(
    name: 'Gooseberry (आंवला)',
    category: 'Fruit',
    image: 'assets/general/fruits/gooseberry.png',
    lives: 'Grows on bushes',
    eats: 'People and animals',
    description: 'Gooseberries are small fruits that can have a sweet or sour taste.',
  ),
  GeneralItem(
    name: 'Apricot (खुबानी)',
    category: 'Fruit',
    image: 'assets/general/fruits/apricot.png',
    lives: 'Grows on apricot trees',
    eats: 'People and animals',
    description: 'Apricots are small orange fruits with soft flesh and one stone.',
  ),
  GeneralItem(
    name: 'Nectarine (नेक्टरीन)',
    category: 'Fruit',
    image: 'assets/general/fruits/nectarine.png',
    lives: 'Grows on nectarine trees',
    eats: 'People and animals',
    description: 'Nectarines are similar to peaches but have smooth skin.',
  ),
  GeneralItem(
    name: 'Cantaloupe (खरबूजा)',
    category: 'Fruit',
    image: 'assets/general/fruits/cantaloupe.png',
    lives: 'Grows on vines along the ground',
    eats: 'People and animals',
    description: 'Cantaloupe is a juicy melon with orange flesh and a sweet taste.',
  ),
  GeneralItem(
    name: 'Muskmelon (खरबूजा)',
    category: 'Fruit',
    image: 'assets/general/fruits/muskmelon.png',
    lives: 'Grows on vines close to the ground',
    eats: 'People and animals',
    description: 'Muskmelon is a sweet and juicy summer fruit.',
  ),
  GeneralItem(
    name: 'Grapefruit (चकोतरा)',
    category: 'Fruit',
    image: 'assets/general/fruits/grapefruit.png',
    lives: 'Grows on citrus trees',
    eats: 'People and animals',
    description: 'Grapefruit is a large citrus fruit with juicy, slightly bitter flesh.',
  ),
  GeneralItem(
    name: 'Mandarin (किन्नू)',
    category: 'Fruit',
    image: 'assets/general/fruits/mandarin.png',
    lives: 'Grows on citrus trees',
    eats: 'People and animals',
    description: 'Mandarins are small citrus fruits that are easy to peel.',
  ),
  GeneralItem(
    name: 'Kumquat (कुमक्वाट)',
    category: 'Fruit',
    image: 'assets/general/fruits/kumquat.png',
    lives: 'Grows on small citrus trees',
    eats: 'People and animals',
    description: 'Kumquats are tiny citrus fruits that can be eaten with their skin.',
  ),
  GeneralItem(
    name: 'Persimmon (तेंदू फल)',
    category: 'Fruit',
    image: 'assets/general/fruits/persimmon.png',
    lives: 'Grows on persimmon trees',
    eats: 'People and animals',
    description: 'Persimmons are orange fruits that become sweet when ripe.',
  ),
  GeneralItem(
    name: 'Rambutan (रामबुतान)',
    category: 'Fruit',
    image: 'assets/general/fruits/rambutan.png',
    lives: 'Grows in clusters on tropical trees',
    eats: 'People and animals',
    description: 'Rambutan has a hairy-looking red or yellow skin and juicy flesh.',
  ),
  GeneralItem(
    name: 'Mangosteen (मैंगोस्टीन)',
    category: 'Fruit',
    image: 'assets/general/fruits/mangosteen.png',
    lives: 'Grows on tropical evergreen trees',
    eats: 'People and animals',
    description: 'Mangosteen has thick purple skin and soft white segments inside.',
  ),
  GeneralItem(
    name: 'Durian (डूरियन)',
    category: 'Fruit',
    image: 'assets/general/fruits/durian.png',
    lives: 'Grows on tall tropical trees',
    eats: 'People and animals',
    description: 'Durian is a large fruit with a spiky shell and a strong smell.',
  ),
  GeneralItem(
    name: 'Soursop (ग्रेविओला)',
    category: 'Fruit',
    image: 'assets/general/fruits/soursop.png',
    lives: 'Grows on tropical trees',
    eats: 'People and animals',
    description: 'Soursop is a green fruit with soft white flesh and a sweet-sour taste.',
  ),
  GeneralItem(
    name: 'Breadfruit (ब्रेडफ्रूट)',
    category: 'Fruit',
    image: 'assets/general/fruits/breadfruit.png',
    lives: 'Grows on tropical trees',
    eats: 'People and animals',
    description: 'Breadfruit is a large green fruit that is often cooked before eating.',
  ),
  GeneralItem(
    name: 'Quince (बिही)',
    category: 'Fruit',
    image: 'assets/general/fruits/quince.png',
    lives: 'Grows on small trees',
    eats: 'People and animals',
    description: 'Quince is a firm yellow fruit that is commonly cooked before eating.',
  ),
  GeneralItem(
    name: 'Cranberry (क्रैनबेरी)',
    category: 'Fruit',
    image: 'assets/general/fruits/cranberry.png',
    lives: 'Grows on low plants in wet areas',
    eats: 'People and animals',
    description: 'Cranberries are small red berries with a naturally sour taste.',
  ),
];