import 'general_data.dart';

final List<GeneralItem> humanBody = [
  GeneralItem(
    name: 'Brain (मस्तिष्क)',
    category: 'Body Part',
    image: 'assets/general/human_body/brain.png',
    lives: '',
    eats: '',
    description: 'The brain controls our thoughts, memory, movements, feelings, and many other activities of the body.',
  ),
  GeneralItem(
    name: 'Heart (हृदय)',
    category: 'Body Part',
    image: 'assets/general/human_body/heart.png',
    lives: '',
    eats: '',
    description: 'The heart pumps blood throughout the body.',
  ),
  GeneralItem(
    name: 'Lungs (फेफड़े)',
    category: 'Body Part',
    image: 'assets/general/human_body/lungs.png',
    lives: '',
    eats: '',
    description: 'The lungs help us breathe by taking in oxygen and removing carbon dioxide.',
  ),
  GeneralItem(
    name: 'Stomach (पेट)',
    category: 'Body Part',
    image: 'assets/general/human_body/stomach.png',
    lives: '',
    eats: '',
    description: 'The stomach helps break down the food we eat.',
  ),
  GeneralItem(
    name: 'Small Intestine (छोटी आंत)',
    category: 'Body Part',
    image: 'assets/general/human_body/small_intestine.png',
    lives: '',
    eats: '',
    description: 'The small intestine absorbs nutrients from digested food.',
  ),
  GeneralItem(
    name: 'Large Intestine (बड़ी आंत)',
    category: 'Body Part',
    image: 'assets/general/human_body/large_intestine.png',
    lives: '',
    eats: '',
    description: 'The large intestine absorbs water and helps form waste.',
  ),
  GeneralItem(
    name: 'Liver (यकृत)',
    category: 'Body Part',
    image: 'assets/general/human_body/liver.png',
    lives: '',
    eats: '',
    description: 'The liver helps process nutrients and removes harmful substances from the blood.',
  ),
  GeneralItem(
    name: 'Kidneys (गुर्दे)',
    category: 'Body Part',
    image: 'assets/general/human_body/kidneys.png',
    lives: '',
    eats: '',
    description: 'The kidneys filter waste and extra water from the blood to make urine.',
  ),
  GeneralItem(
    name: 'Eyes (आंखें)',
    category: 'Body Part',
    image: 'assets/general/human_body/eyes.png',
    lives: '',
    eats: '',
    description: 'The eyes help us see colours, shapes, people, and objects around us.',
  ),
  GeneralItem(
    name: 'Ears (कान)',
    category: 'Body Part',
    image: 'assets/general/human_body/ears.png',
    lives: '',
    eats: '',
    description: 'The ears help us hear sounds and also help us maintain balance.',
  ),
  GeneralItem(
    name: 'Nose (नाक)',
    category: 'Body Part',
    image: 'assets/general/human_body/nose.png',
    lives: '',
    eats: '',
    description: 'The nose helps us smell and also helps air enter the body when we breathe.',
  ),
  GeneralItem(
    name: 'Tongue (जीभ)',
    category: 'Body Part',
    image: 'assets/general/human_body/tongue.png',
    lives: '',
    eats: '',
    description: 'The tongue helps us taste food, speak, and move food around the mouth.',
  ),
  GeneralItem(
    name: 'Teeth (दांत)',
    category: 'Body Part',
    image: 'assets/general/human_body/teeth.png',
    lives: '',
    eats: '',
    description: 'Teeth help us bite and chew food.',
  ),
  GeneralItem(
    name: 'Mouth (मुंह)',
    category: 'Body Part',
    image: 'assets/general/human_body/mouth.png',
    lives: '',
    eats: '',
    description: 'The mouth helps us eat, drink, speak, and begin digestion.',
  ),
  GeneralItem(
    name: 'Skin (त्वचा)',
    category: 'Body Part',
    image: 'assets/general/human_body/skin.png',
    lives: '',
    eats: '',
    description: 'Skin covers and protects the body and helps us feel touch, heat, and cold.',
  ),
  GeneralItem(
    name: 'Bones (हड्डियां)',
    category: 'Body Part',
    image: 'assets/general/human_body/bones.png',
    lives: '',
    eats: '',
    description: 'Bones give our body shape and support and protect important organs.',
  ),
  GeneralItem(
    name: 'Muscles (मांसपेशियां)',
    category: 'Body Part',
    image: 'assets/general/human_body/muscles.png',
    lives: '',
    eats: '',
    description: 'Muscles help us move our body and perform different activities.',
  ),
  GeneralItem(
    name: 'Blood (रक्त)',
    category: 'Body Part',
    image: 'assets/general/human_body/blood.png',
    lives: '',
    eats: '',
    description: 'Blood carries oxygen and nutrients around the body and carries away waste.',
  ),
  GeneralItem(
    name: 'Spine (रीढ़ की हड्डी)',
    category: 'Body Part',
    image: 'assets/general/human_body/spine.png',
    lives: '',
    eats: '',
    description: 'The spine supports the body and protects the spinal cord.',
  ),
  GeneralItem(
    name: 'Spinal Cord (रीढ़ की हड्डी की नस)',
    category: 'Body Part',
    image: 'assets/general/human_body/spinal_cord.png',
    lives: '',
    eats: '',
    description: 'The spinal cord carries messages between the brain and the rest of the body.',
  ),
  GeneralItem(
    name: 'Shoulder (कंधा)',
    category: 'Body Part',
    image: 'assets/general/human_body/shoulder.png',
    lives: '',
    eats: '',
    description: 'The shoulder connects the arm to the body and allows the arm to move.',
  ),
  GeneralItem(
    name: 'Arm (बांह)',
    category: 'Body Part',
    image: 'assets/general/human_body/arm.png',
    lives: '',
    eats: '',
    description: 'The arms help us lift, carry, push, pull, and reach objects.',
  ),
  GeneralItem(
    name: 'Elbow (कोहनी)',
    category: 'Body Part',
    image: 'assets/general/human_body/elbow.png',
    lives: '',
    eats: '',
    description: 'The elbow is a joint that allows the arm to bend and straighten.',
  ),
  GeneralItem(
    name: 'Wrist (कलाई)',
    category: 'Body Part',
    image: 'assets/general/human_body/wrist.png',
    lives: '',
    eats: '',
    description: 'The wrist connects the hand to the arm and helps the hand move.',
  ),
  GeneralItem(
    name: 'Hand (हाथ)',
    category: 'Body Part',
    image: 'assets/general/human_body/hand.png',
    lives: '',
    eats: '',
    description: 'Hands help us hold, touch, write, pick up, and use objects.',
  ),
  GeneralItem(
    name: 'Fingers (उंगलियां)',
    category: 'Body Part',
    image: 'assets/general/human_body/fingers.png',
    lives: '',
    eats: '',
    description: 'Fingers help us grip, touch, write, and perform small movements.',
  ),
  GeneralItem(
    name: 'Chest (छाती)',
    category: 'Body Part',
    image: 'assets/general/human_body/chest.png',
    lives: '',
    eats: '',
    description: 'The chest protects important organs such as the heart and lungs.',
  ),
  GeneralItem(
    name: 'Leg (पैर)',
    category: 'Body Part',
    image: 'assets/general/human_body/leg.png',
    lives: '',
    eats: '',
    description: 'The legs help us stand, walk, run, jump, and move around.',
  ),
  GeneralItem(
    name: 'Knee (घुटना)',
    category: 'Body Part',
    image: 'assets/general/human_body/knee.png',
    lives: '',
    eats: '',
    description: 'The knee is a joint that helps the leg bend and straighten.',
  ),
  GeneralItem(
    name: 'Ankle (टखना)',
    category: 'Body Part',
    image: 'assets/general/human_body/ankle.png',
    lives: '',
    eats: '',
    description: 'The ankle connects the foot to the leg and helps with movement and balance.',
  ),
  GeneralItem(
    name: 'Foot (पैर का पंजा)',
    category: 'Body Part',
    image: 'assets/general/human_body/foot.png',
    lives: '',
    eats: '',
    description: 'The feet support our body and help us walk, run, and stand.',
  ),
  GeneralItem(
    name: 'Toes (पैर की उंगलियां)',
    category: 'Body Part',
    image: 'assets/general/human_body/toes.png',
    lives: '',
    eats: '',
    description: 'Toes help us maintain balance while standing and walking.',
  ),
  GeneralItem(
    name: 'Neck (गर्दन)',
    category: 'Body Part',
    image: 'assets/general/human_body/neck.png',
    lives: '',
    eats: '',
    description: 'The neck connects the head to the body and allows the head to move.',
  ),
  GeneralItem(
    name: 'Throat (गला)',
    category: 'Body Part',
    image: 'assets/general/human_body/throat.png',
    lives: '',
    eats: '',
    description: 'The throat is a passage used for breathing and swallowing.',
  ),
  GeneralItem(
    name: 'Pancreas (अग्न्याशय)',
    category: 'Body Part',
    image: 'assets/general/human_body/pancreas.png',
    lives: '',
    eats: '',
    description: 'The pancreas helps digest food and helps control blood sugar.',
  ),
  GeneralItem(
    name: 'Bladder (मूत्राशय)',
    category: 'Body Part',
    image: 'assets/general/human_body/bladder.png',
    lives: '',
    eats: '',
    description: 'The bladder stores urine until it leaves the body.',
  ),
  GeneralItem(
    name: 'Ribs (पसलियां)',
    category: 'Body Part',
    image: 'assets/general/human_body/ribs.png',
    lives: '',
    eats: '',
    description: 'The ribs form a protective cage around the heart and lungs.',
  ),
  GeneralItem(
    name: 'Eyebrows (भौंहें)',
    category: 'Body Part',
    image: 'assets/general/human_body/eyebrows.png',
    lives: '',
    eats: '',
    description: 'Eyebrows help keep sweat and moisture away from the eyes.',
  ),
  GeneralItem(
    name: 'Eyelashes (पलकें)',
    category: 'Body Part',
    image: 'assets/general/human_body/eyelashes.png',
    lives: '',
    eats: '',
    description: 'Eyelashes help protect the eyes from dust and small particles.',
  ),
  GeneralItem(
    name: 'Hair (बाल)',
    category: 'Body Part',
    image: 'assets/general/human_body/hair.png',
    lives: '',
    eats: '',
    description: 'Hair grows from the skin and helps protect the head and scalp.',
  ),
  GeneralItem(
    name: 'Nails (नाखून)',
    category: 'Body Part',
    image: 'assets/general/human_body/nails.png',
    lives: '',
    eats: '',
    description: 'Nails protect the tips of our fingers and toes.',
  ),
];