import 'general_data.dart';

final List<GeneralItem> materialsAroundUs = [
  GeneralItem(
    name: 'Wood (लकड़ी)',
    category: 'Material',
    image: 'assets/general/materials_around_us/wood.png',
    lives: '',
    eats: '',
    description: 'Wood comes from trees and is used to make furniture, doors, paper, and many other things.',
  ),
  GeneralItem(
    name: 'Metal (धातु)',
    category: 'Material',
    image: 'assets/general/materials_around_us/metal.png',
    lives: '',
    eats: '',
    description: 'Metal is strong and is used to make tools, machines, vehicles, and many household objects.',
  ),
  GeneralItem(
    name: 'Iron (लोहा)',
    category: 'Material',
    image: 'assets/general/materials_around_us/iron.png',
    lives: '',
    eats: '',
    description: 'Iron is a strong metal used in buildings, tools, machines, and many other objects.',
  ),
  GeneralItem(
    name: 'Steel (इस्पात)',
    category: 'Material',
    image: 'assets/general/materials_around_us/steel.png',
    lives: '',
    eats: '',
    description: 'Steel is a strong material made mainly from iron and is used in buildings, vehicles, and tools.',
  ),
  GeneralItem(
    name: 'Copper (तांबा)',
    category: 'Material',
    image: 'assets/general/materials_around_us/copper.png',
    lives: '',
    eats: '',
    description: 'Copper is a metal commonly used in electrical wires and some household objects.',
  ),
  GeneralItem(
    name: 'Aluminium (एल्युमिनियम)',
    category: 'Material',
    image: 'assets/general/materials_around_us/aluminium.png',
    lives: '',
    eats: '',
    description: 'Aluminium is a light metal used in cans, utensils, vehicles, and aircraft.',
  ),
  GeneralItem(
    name: 'Gold (सोना)',
    category: 'Material',
    image: 'assets/general/materials_around_us/gold.png',
    lives: '',
    eats: '',
    description: 'Gold is a valuable metal commonly used to make jewellery.',
  ),
  GeneralItem(
    name: 'Silver (चांदी)',
    category: 'Material',
    image: 'assets/general/materials_around_us/silver.png',
    lives: '',
    eats: '',
    description: 'Silver is a shiny metal used in jewellery, utensils, and some electronic products.',
  ),
  GeneralItem(
    name: 'Glass (कांच)',
    category: 'Material',
    image: 'assets/general/materials_around_us/glass.png',
    lives: '',
    eats: '',
    description: 'Glass is a hard and usually transparent material used for windows, bottles, and mirrors.',
  ),
  GeneralItem(
    name: 'Plastic (प्लास्टिक)',
    category: 'Material',
    image: 'assets/general/materials_around_us/plastic.png',
    lives: '',
    eats: '',
    description: 'Plastic is a lightweight material used to make bottles, containers, toys, and many other things.',
  ),
  GeneralItem(
    name: 'Paper (कागज)',
    category: 'Material',
    image: 'assets/general/materials_around_us/paper.png',
    lives: '',
    eats: '',
    description: 'Paper is mainly made from plant fibres and is used for books, notebooks, and writing.',
  ),
  GeneralItem(
    name: 'Cardboard (गत्ता)',
    category: 'Material',
    image: 'assets/general/materials_around_us/cardboard.png',
    lives: '',
    eats: '',
    description: 'Cardboard is a thick paper material commonly used for boxes and packaging.',
  ),
  GeneralItem(
    name: 'Cotton (कपास)',
    category: 'Material',
    image: 'assets/general/materials_around_us/cotton.png',
    lives: '',
    eats: '',
    description: 'Cotton is a soft natural fibre used to make clothes, towels, and other fabrics.',
  ),
  GeneralItem(
    name: 'Wool (ऊन)',
    category: 'Material',
    image: 'assets/general/materials_around_us/wool.png',
    lives: '',
    eats: '',
    description: 'Wool is a warm natural fibre commonly used to make sweaters, blankets, and winter clothing.',
  ),
  GeneralItem(
    name: 'Silk (रेशम)',
    category: 'Material',
    image: 'assets/general/materials_around_us/silk.png',
    lives: '',
    eats: '',
    description: 'Silk is a smooth and shiny natural fibre used to make clothing and other fabrics.',
  ),
  GeneralItem(
    name: 'Leather (चमड़ा)',
    category: 'Material',
    image: 'assets/general/materials_around_us/leather.png',
    lives: '',
    eats: '',
    description: 'Leather is a strong material used to make shoes, bags, belts, and other products.',
  ),
  GeneralItem(
    name: 'Rubber (रबर)',
    category: 'Material',
    image: 'assets/general/materials_around_us/rubber.png',
    lives: '',
    eats: '',
    description: 'Rubber is flexible and is used to make tyres, erasers, gloves, and many other products.',
  ),
  GeneralItem(
    name: 'Clay (मिट्टी)',
    category: 'Material',
    image: 'assets/general/materials_around_us/clay.png',
    lives: '',
    eats: '',
    description: 'Clay is a soft natural material used to make pots, bricks, and pottery.',
  ),
  GeneralItem(
    name: 'Brick (ईंट)',
    category: 'Material',
    image: 'assets/general/materials_around_us/brick.png',
    lives: '',
    eats: '',
    description: 'Bricks are hard building materials commonly used to construct walls and houses.',
  ),
  GeneralItem(
    name: 'Cement (सीमेंट)',
    category: 'Material',
    image: 'assets/general/materials_around_us/cement.png',
    lives: '',
    eats: '',
    description: 'Cement is a powder used with other materials to make strong building structures.',
  ),
  GeneralItem(
    name: 'Concrete (कंक्रीट)',
    category: 'Material',
    image: 'assets/general/materials_around_us/concrete.png',
    lives: '',
    eats: '',
    description: 'Concrete is a strong building material used for roads, bridges, floors, and buildings.',
  ),
  GeneralItem(
    name: 'Stone (पत्थर)',
    category: 'Material',
    image: 'assets/general/materials_around_us/stone.png',
    lives: '',
    eats: '',
    description: 'Stone is a natural hard material used in buildings, roads, and monuments.',
  ),
  GeneralItem(
    name: 'Marble (संगमरमर)',
    category: 'Material',
    image: 'assets/general/materials_around_us/marble.png',
    lives: '',
    eats: '',
    description: 'Marble is a smooth natural stone used for floors, walls, statues, and decoration.',
  ),
  GeneralItem(
    name: 'Granite (ग्रेनाइट)',
    category: 'Material',
    image: 'assets/general/materials_around_us/granite.png',
    lives: '',
    eats: '',
    description: 'Granite is a hard natural stone commonly used for floors, countertops, and buildings.',
  ),
  GeneralItem(
    name: 'Sand (रेत)',
    category: 'Material',
    image: 'assets/general/materials_around_us/sand.png',
    lives: '',
    eats: '',
    description: 'Sand is made of tiny rock particles and is used in construction and glass making.',
  ),
  GeneralItem(
    name: 'Soil (मिट्टी)',
    category: 'Material',
    image: 'assets/general/materials_around_us/soil.png',
    lives: '',
    eats: '',
    description: 'Soil is the upper layer of Earth where many plants grow.',
  ),
  GeneralItem(
    name: 'Water (पानी)',
    category: 'Material',
    image: 'assets/general/materials_around_us/water.png',
    lives: '',
    eats: '',
    description: 'Water is a liquid that is essential for people, animals, plants, and many daily activities.',
  ),
  GeneralItem(
    name: 'Ice (बर्फ)',
    category: 'Material',
    image: 'assets/general/materials_around_us/ice.png',
    lives: '',
    eats: '',
    description: 'Ice is the solid form of water and is formed when water freezes.',
  ),
  GeneralItem(
    name: 'Salt (नमक)',
    category: 'Material',
    image: 'assets/general/materials_around_us/salt.png',
    lives: '',
    eats: '',
    description: 'Salt is a mineral commonly used to add taste to food.',
  ),
  GeneralItem(
    name: 'Cotton Fabric (सूती कपड़ा)',
    category: 'Material',
    image: 'assets/general/materials_around_us/cotton_fabric.png',
    lives: '',
    eats: '',
    description: 'Cotton fabric is made from cotton fibres and is commonly used for comfortable clothing.',
  ),
  GeneralItem(
    name: 'Nylon (नायलॉन)',
    category: 'Material',
    image: 'assets/general/materials_around_us/nylon.png',
    lives: '',
    eats: '',
    description: 'Nylon is a strong synthetic material used in clothes, ropes, bags, and other products.',
  ),
  GeneralItem(
    name: 'Polyester (पॉलिएस्टर)',
    category: 'Material',
    image: 'assets/general/materials_around_us/polyester.png',
    lives: '',
    eats: '',
    description: 'Polyester is a synthetic fibre widely used to make clothing and fabrics.',
  ),
  GeneralItem(
    name: 'Foam (फोम)',
    category: 'Material',
    image: 'assets/general/materials_around_us/foam.png',
    lives: '',
    eats: '',
    description: 'Foam is a lightweight material used in mattresses, cushions, packaging, and other products.',
  ),
  GeneralItem(
    name: 'Sponge (स्पंज)',
    category: 'Material',
    image: 'assets/general/materials_around_us/sponge.png',
    lives: '',
    eats: '',
    description: 'A sponge is a soft material that can absorb and hold water.',
  ),
  GeneralItem(
    name: 'Wax (मोम)',
    category: 'Material',
    image: 'assets/general/materials_around_us/wax.png',
    lives: '',
    eats: '',
    description: 'Wax is a material used to make candles, crayons, and other products.',
  ),
  GeneralItem(
    name: 'Chalk (चॉक)',
    category: 'Material',
    image: 'assets/general/materials_around_us/chalk.png',
    lives: '',
    eats: '',
    description: 'Chalk is a soft material used for writing and drawing on suitable surfaces.',
  ),
  GeneralItem(
    name: 'Graphite (ग्रेफाइट)',
    category: 'Material',
    image: 'assets/general/materials_around_us/graphite.png',
    lives: '',
    eats: '',
    description: 'Graphite is a form of carbon commonly used inside pencils for writing.',
  ),
  GeneralItem(
    name: 'Ceramic (सिरेमिक)',
    category: 'Material',
    image: 'assets/general/materials_around_us/ceramic.png',
    lives: '',
    eats: '',
    description: 'Ceramic is a hard material used to make plates, cups, tiles, and decorative objects.',
  ),
  GeneralItem(
    name: 'Porcelain (चीनी मिट्टी)',
    category: 'Material',
    image: 'assets/general/materials_around_us/porcelain.png',
    lives: '',
    eats: '',
    description: 'Porcelain is a smooth and hard ceramic material used for dishes and decorative objects.',
  ),
  GeneralItem(
    name: 'Bamboo (बांस)',
    category: 'Material',
    image: 'assets/general/materials_around_us/bamboo.png',
    lives: '',
    eats: '',
    description: 'Bamboo is a strong plant material used to make furniture, baskets, and many other things.',
  ),
  GeneralItem(
    name: 'Jute (जूट)',
    category: 'Material',
    image: 'assets/general/materials_around_us/jute.png',
    lives: '',
    eats: '',
    description: 'Jute is a natural plant fibre used to make bags, ropes, mats, and other products.',
  ),
  GeneralItem(
    name: 'Cork (कॉर्क)',
    category: 'Material',
    image: 'assets/general/materials_around_us/cork.png',
    lives: '',
    eats: '',
    description: 'Cork is a lightweight material obtained from the bark of certain trees.',
  ),
  GeneralItem(
    name: 'Paperboard (कागजी गत्ता)',
    category: 'Material',
    image: 'assets/general/materials_around_us/paperboard.png',
    lives: '',
    eats: '',
    description: 'Paperboard is thicker than ordinary paper and is used for packaging and cards.',
  ),
  GeneralItem(
    name: 'Foil (धातु की पन्नी)',
    category: 'Material',
    image: 'assets/general/materials_around_us/foil.png',
    lives: '',
    eats: '',
    description: 'Metal foil is a very thin sheet of metal used for wrapping and packaging.',
  ),
  GeneralItem(
    name: 'Ceramic Tile (सिरेमिक टाइल)',
    category: 'Material',
    image: 'assets/general/materials_around_us/ceramic_tile.png',
    lives: '',
    eats: '',
    description: 'Ceramic tiles are hard materials commonly used on floors and walls.',
  ),
  GeneralItem(
    name: 'Thread (धागा)',
    category: 'Material',
    image: 'assets/general/materials_around_us/thread.png',
    lives: '',
    eats: '',
    description: 'Thread is a thin strand of fibre used for sewing and making fabrics.',
  ),
  GeneralItem(
    name: 'Rope (रस्सी)',
    category: 'Material',
    image: 'assets/general/materials_around_us/rope.png',
    lives: '',
    eats: '',
    description: 'Rope is made by twisting or braiding fibres and is used for tying and lifting things.',
  ),
  GeneralItem(
    name: 'Fabric (कपड़ा)',
    category: 'Material',
    image: 'assets/general/materials_around_us/fabric.png',
    lives: '',
    eats: '',
    description: 'Fabric is made from fibres and is used to make clothes, curtains, bags, and many other items.',
  ),
  GeneralItem(
    name: 'Wood Pulp (लकड़ी का गूदा)',
    category: 'Material',
    image: 'assets/general/materials_around_us/wood_pulp.png',
    lives: '',
    eats: '',
    description: 'Wood pulp is made from plant fibres and is used to manufacture paper.',
  ),
  GeneralItem(
    name: 'Carbon (कार्बन)',
    category: 'Material',
    image: 'assets/general/materials_around_us/carbon.png',
    lives: '',
    eats: '',
    description: 'Carbon is an element found in many living things and many useful materials.',
  ),
  GeneralItem(
    name: 'Clay Pot (मिट्टी का बर्तन)',
    category: 'Material',
    image: 'assets/general/materials_around_us/clay_pot.png',
    lives: '',
    eats: '',
    description: 'Clay pots are made by shaping and heating clay until it becomes hard.',
  ),
  GeneralItem(
    name: 'Glass Fibre (कांच का रेशा)',
    category: 'Material',
    image: 'assets/general/materials_around_us/glass_fibre.png',
    lives: '',
    eats: '',
    description: 'Glass fibre consists of very thin glass strands and is used in many strong materials.',
  ),
  GeneralItem(
    name: 'Recycled Paper (पुनर्चक्रित कागज)',
    category: 'Material',
    image: 'assets/general/materials_around_us/recycled_paper.png',
    lives: '',
    eats: '',
    description: 'Recycled paper is made by processing used paper so it can be used again.',
  ),
];