import 'general_data.dart';

final List<GeneralItem> musicalInstruments = [
  GeneralItem(
    name: 'Piano (पियानो)',
    category: 'Musical Instrument',
    image: 'assets/general/musical_instruments/piano.png',
    lives: '',
    eats: '',
    description: 'A piano has keys that produce musical sounds when pressed.',
  ),
  GeneralItem(
    name: 'Guitar (गिटार)',
    category: 'Musical Instrument',
    image: 'assets/general/musical_instruments/guitar.png',
    lives: '',
    eats: '',
    description: 'A guitar has strings that are plucked or strummed to make music.',
  ),
  GeneralItem(
    name: 'Violin (वायलिन)',
    category: 'Musical Instrument',
    image: 'assets/general/musical_instruments/violin.png',
    lives: '',
    eats: '',
    description: 'A violin has four strings and is usually played with a bow.',
  ),
  GeneralItem(
    name: 'Flute (बांसुरी)',
    category: 'Musical Instrument',
    image: 'assets/general/musical_instruments/flute.png',
    lives: '',
    eats: '',
    description: 'A flute produces sound when air is blown through it.',
  ),
  GeneralItem(
    name: 'Tabla (तबला)',
    category: 'Musical Instrument',
    image: 'assets/general/musical_instruments/tabla.png',
    lives: '',
    eats: '',
    description: 'Tabla is a pair of drums played with the hands and fingers.',
  ),
  GeneralItem(
    name: 'Drum (ढोल)',
    category: 'Musical Instrument',
    image: 'assets/general/musical_instruments/drum.png',
    lives: '',
    eats: '',
    description: 'A drum produces sound when its stretched surface is struck.',
  ),
  GeneralItem(
    name: 'Dholak (ढोलक)',
    category: 'Musical Instrument',
    image: 'assets/general/musical_instruments/dholak.png',
    lives: '',
    eats: '',
    description: 'Dholak is a traditional Indian drum played with the hands.',
  ),
  GeneralItem(
    name: 'Harmonium (हारमोनियम)',
    category: 'Musical Instrument',
    image: 'assets/general/musical_instruments/harmonium.png',
    lives: '',
    eats: '',
    description: 'A harmonium produces sound using air and keys.',
  ),
  GeneralItem(
    name: 'Sitar (सितार)',
    category: 'Musical Instrument',
    image: 'assets/general/musical_instruments/sitar.png',
    lives: '',
    eats: '',
    description: 'The sitar is a string instrument commonly used in Indian classical music.',
  ),
  GeneralItem(
    name: 'Sarod (सरोद)',
    category: 'Musical Instrument',
    image: 'assets/general/musical_instruments/sarod.png',
    lives: '',
    eats: '',
    description: 'Sarod is a string instrument used in Indian classical music.',
  ),
  GeneralItem(
    name: 'Veena (वीणा)',
    category: 'Musical Instrument',
    image: 'assets/general/musical_instruments/veena.png',
    lives: '',
    eats: '',
    description: 'Veena is an important Indian string instrument used in classical music.',
  ),
  GeneralItem(
    name: 'Santoor (संतूर)',
    category: 'Musical Instrument',
    image: 'assets/general/musical_instruments/santoor.png',
    lives: '',
    eats: '',
    description: 'Santoor has many strings and is played by striking them with small mallets.',
  ),
  GeneralItem(
    name: 'Shehnai (शहनाई)',
    category: 'Musical Instrument',
    image: 'assets/general/musical_instruments/shehnai.png',
    lives: '',
    eats: '',
    description: 'Shehnai is a wind instrument known for its bright and powerful sound.',
  ),
  GeneralItem(
    name: 'Trumpet (तुरही)',
    category: 'Musical Instrument',
    image: 'assets/general/musical_instruments/trumpet.png',
    lives: '',
    eats: '',
    description: 'A trumpet is a brass instrument played by blowing air through a mouthpiece.',
  ),
  GeneralItem(
    name: 'Trombone (ट्रॉम्बोन)',
    category: 'Musical Instrument',
    image: 'assets/general/musical_instruments/trombone.png',
    lives: '',
    eats: '',
    description: 'A trombone is a brass instrument with a sliding tube used to change notes.',
  ),
  GeneralItem(
    name: 'French Horn (फ्रेंच हॉर्न)',
    category: 'Musical Instrument',
    image: 'assets/general/musical_instruments/french_horn.png',
    lives: '',
    eats: '',
    description: 'The French horn is a brass instrument with a long coiled tube.',
  ),
  GeneralItem(
    name: 'Tuba (ट्यूबा)',
    category: 'Musical Instrument',
    image: 'assets/general/musical_instruments/tuba.png',
    lives: '',
    eats: '',
    description: 'The tuba is a large brass instrument that produces deep sounds.',
  ),
  GeneralItem(
    name: 'Clarinet (क्लैरिनेट)',
    category: 'Musical Instrument',
    image: 'assets/general/musical_instruments/clarinet.png',
    lives: '',
    eats: '',
    description: 'A clarinet is a woodwind instrument played by blowing air through a reed.',
  ),
  GeneralItem(
    name: 'Saxophone (सैक्सोफोन)',
    category: 'Musical Instrument',
    image: 'assets/general/musical_instruments/saxophone.png',
    lives: '',
    eats: '',
    description: 'A saxophone is a wind instrument with keys and a single reed.',
  ),
  GeneralItem(
    name: 'Oboe (ओबो)',
    category: 'Musical Instrument',
    image: 'assets/general/musical_instruments/oboe.png',
    lives: '',
    eats: '',
    description: 'An oboe is a woodwind instrument played using a double reed.',
  ),
  GeneralItem(
    name: 'Bassoon (बेसून)',
    category: 'Musical Instrument',
    image: 'assets/general/musical_instruments/bassoon.png',
    lives: '',
    eats: '',
    description: 'A bassoon is a large woodwind instrument with a deep sound.',
  ),
  GeneralItem(
    name: 'Harp (वीणा जैसा हार्प)',
    category: 'Musical Instrument',
    image: 'assets/general/musical_instruments/harp.png',
    lives: '',
    eats: '',
    description: 'A harp has many strings that are plucked with the fingers.',
  ),
  GeneralItem(
    name: 'Cello (चेलो)',
    category: 'Musical Instrument',
    image: 'assets/general/musical_instruments/cello.png',
    lives: '',
    eats: '',
    description: 'A cello is a large string instrument usually played with a bow.',
  ),
  GeneralItem(
    name: 'Double Bass (डबल बेस)',
    category: 'Musical Instrument',
    image: 'assets/general/musical_instruments/double_bass.png',
    lives: '',
    eats: '',
    description: 'The double bass is a very large string instrument with deep sounds.',
  ),
  GeneralItem(
    name: 'Ukulele (यूकुलेले)',
    category: 'Musical Instrument',
    image: 'assets/general/musical_instruments/ukulele.png',
    lives: '',
    eats: '',
    description: 'A ukulele is a small string instrument similar to a guitar.',
  ),
  GeneralItem(
    name: 'Mandolin (मैंडोलिन)',
    category: 'Musical Instrument',
    image: 'assets/general/musical_instruments/mandolin.png',
    lives: '',
    eats: '',
    description: 'A mandolin is a small string instrument usually played with a pick.',
  ),
  GeneralItem(
    name: 'Banjo (बैंजो)',
    category: 'Musical Instrument',
    image: 'assets/general/musical_instruments/banjo.png',
    lives: '',
    eats: '',
    description: 'A banjo is a string instrument with a round body and a long neck.',
  ),
  GeneralItem(
    name: 'Accordion (अकॉर्डियन)',
    category: 'Musical Instrument',
    image: 'assets/general/musical_instruments/accordion.png',
    lives: '',
    eats: '',
    description: 'An accordion produces sound by pushing and pulling its bellows while pressing keys or buttons.',
  ),
  GeneralItem(
    name: 'Harmonica (हारमोनिका)',
    category: 'Musical Instrument',
    image: 'assets/general/musical_instruments/harmonica.png',
    lives: '',
    eats: '',
    description: 'A harmonica is a small wind instrument played by blowing and drawing air through it.',
  ),
  GeneralItem(
    name: 'Recorder (रिकॉर्डर)',
    category: 'Musical Instrument',
    image: 'assets/general/musical_instruments/recorder.png',
    lives: '',
    eats: '',
    description: 'A recorder is a simple wind instrument with holes that are covered to change notes.',
  ),
  GeneralItem(
    name: 'Xylophone (ज़ाइलोफोन)',
    category: 'Musical Instrument',
    image: 'assets/general/musical_instruments/xylophone.png',
    lives: '',
    eats: '',
    description: 'A xylophone has wooden bars that are struck with mallets.',
  ),
  GeneralItem(
    name: 'Marimba (मैरिम्बा)',
    category: 'Musical Instrument',
    image: 'assets/general/musical_instruments/marimba.png',
    lives: '',
    eats: '',
    description: 'A marimba has wooden bars that are struck with mallets to produce musical notes.',
  ),
  GeneralItem(
    name: 'Glockenspiel (ग्लॉकेंश्पील)',
    category: 'Musical Instrument',
    image: 'assets/general/musical_instruments/glockenspiel.png',
    lives: '',
    eats: '',
    description: 'A glockenspiel has metal bars that are struck with mallets.',
  ),
  GeneralItem(
    name: 'Cymbals (झांझ)',
    category: 'Musical Instrument',
    image: 'assets/general/musical_instruments/cymbals.png',
    lives: '',
    eats: '',
    description: 'Cymbals are metal discs that are struck together to create a bright sound.',
  ),
  GeneralItem(
    name: 'Triangle (ट्रायंगल)',
    category: 'Musical Instrument',
    image: 'assets/general/musical_instruments/triangle.png',
    lives: '',
    eats: '',
    description: 'A triangle is a metal instrument that is struck with a small beater.',
  ),
  GeneralItem(
    name: 'Tambourine (टैम्बरीन)',
    category: 'Musical Instrument',
    image: 'assets/general/musical_instruments/tambourine.png',
    lives: '',
    eats: '',
    description: 'A tambourine is a small frame drum with metal jingles around its edge.',
  ),
  GeneralItem(
    name: 'Bongo Drums (बोंगो ड्रम)',
    category: 'Musical Instrument',
    image: 'assets/general/musical_instruments/bongo.png',
    lives: '',
    eats: '',
    description: 'Bongo drums are a pair of small drums played with the hands.',
  ),
  GeneralItem(
    name: 'Congas (कोंगा)',
    category: 'Musical Instrument',
    image: 'assets/general/musical_instruments/congas.png',
    lives: '',
    eats: '',
    description: 'Congas are tall drums played with the hands.',
  ),
  GeneralItem(
    name: 'Maracas (मराकास)',
    category: 'Musical Instrument',
    image: 'assets/general/musical_instruments/maracas.png',
    lives: '',
    eats: '',
    description: 'Maracas are shaken to produce a rhythmic rattling sound.',
  ),
  GeneralItem(
    name: 'Castanets (कास्टनेट्स)',
    category: 'Musical Instrument',
    image: 'assets/general/musical_instruments/castanets.png',
    lives: '',
    eats: '',
    description: 'Castanets are small wooden pieces clicked together to create rhythm.',
  ),
  GeneralItem(
    name: 'Bagpipes (बैगपाइप्स)',
    category: 'Musical Instrument',
    image: 'assets/general/musical_instruments/bagpipes.png',
    lives: '',
    eats: '',
    description: 'Bagpipes use air stored in a bag to produce musical sounds through pipes.',
  ),
  GeneralItem(
    name: 'Didgeridoo (डिड्ज़रिडू)',
    category: 'Musical Instrument',
    image: 'assets/general/musical_instruments/didgeridoo.png',
    lives: '',
    eats: '',
    description: 'The didgeridoo is a traditional Australian wind instrument that produces a deep sound.',
  ),
  GeneralItem(
    name: 'Kalimba (कालिम्बा)',
    category: 'Musical Instrument',
    image: 'assets/general/musical_instruments/kalimba.png',
    lives: '',
    eats: '',
    description: 'A kalimba is played by plucking metal keys with the thumbs.',
  ),
  GeneralItem(
    name: 'Harp Guitar (हार्प गिटार)',
    category: 'Musical Instrument',
    image: 'assets/general/musical_instruments/harp_guitar.png',
    lives: '',
    eats: '',
    description: 'A harp guitar combines features of a guitar with additional strings.',
  ),
  GeneralItem(
    name: 'Electric Guitar (इलेक्ट्रिक गिटार)',
    category: 'Musical Instrument',
    image: 'assets/general/musical_instruments/electric_guitar.png',
    lives: '',
    eats: '',
    description: 'An electric guitar uses electronic pickups and an amplifier to produce sound.',
  ),
  GeneralItem(
    name: 'Electric Keyboard (इलेक्ट्रॉनिक कीबोर्ड)',
    category: 'Musical Instrument',
    image: 'assets/general/musical_instruments/keyboard.png',
    lives: '',
    eats: '',
    description: 'An electronic keyboard uses keys and electronics to create different musical sounds.',
  ),
  GeneralItem(
    name: 'Mridangam (मृदंगम)',
    category: 'Musical Instrument',
    image: 'assets/general/musical_instruments/mridangam.png',
    lives: '',
    eats: '',
    description: 'Mridangam is a traditional Indian percussion instrument used in classical music.',
  ),
  GeneralItem(
    name: 'Nadaswaram (नादस्वरम)',
    category: 'Musical Instrument',
    image: 'assets/general/musical_instruments/nadaswaram.png',
    lives: '',
    eats: '',
    description: 'Nadaswaram is a traditional Indian wind instrument with a strong sound.',
  ),
  GeneralItem(
    name: 'Pungi (पुंगी)',
    category: 'Musical Instrument',
    image: 'assets/general/musical_instruments/pungi.png',
    lives: '',
    eats: '',
    description: 'Pungi is a traditional Indian wind instrument that uses a gourd and pipes.',
  ),
  GeneralItem(
    name: 'Ektara (एकतारा)',
    category: 'Musical Instrument',
    image: 'assets/general/musical_instruments/ektara.png',
    lives: '',
    eats: '',
    description: 'Ektara is a simple traditional string instrument with one main string.',
  ),
  GeneralItem(
    name: 'Ghatam (घटम)',
    category: 'Musical Instrument',
    image: 'assets/general/musical_instruments/ghatam.png',
    lives: '',
    eats: '',
    description: 'Ghatam is a clay percussion instrument played with the hands.',
  ),
  GeneralItem(
    name: 'Manjira (मंजीरा)',
    category: 'Musical Instrument',
    image: 'assets/general/musical_instruments/manjira.png',
    lives: '',
    eats: '',
    description: 'Manjira consists of small metal cymbals that are struck together to create rhythm.',
  ),
];