import 'general_data.dart';

final List<GeneralItem> places = [
  GeneralItem(
    name: 'School (विद्यालय)',
    category: 'Place',
    image: 'assets/general/places/school.png',
    lives: 'Found in towns and cities',
    eats: 'Not applicable',
    description: 'A school is a place where children learn different subjects and skills.',
  ),
  GeneralItem(
    name: 'Hospital (अस्पताल)',
    category: 'Place',
    image: 'assets/general/places/hospital.png',
    lives: 'Found in towns and cities',
    eats: 'Not applicable',
    description: 'A hospital is a place where doctors and nurses treat sick and injured people.',
  ),
  GeneralItem(
    name: 'Park (उद्यान)',
    category: 'Place',
    image: 'assets/general/places/park.png',
    lives: 'Found in towns and cities',
    eats: 'Not applicable',
    description: 'A park is a green place where people can walk, play, and relax.',
  ),
  GeneralItem(
    name: 'Library (पुस्तकालय)',
    category: 'Place',
    image: 'assets/general/places/library.png',
    lives: 'Found in schools and communities',
    eats: 'Not applicable',
    description: 'A library is a place where people can read and borrow books.',
  ),
  GeneralItem(
    name: 'Museum (संग्रहालय)',
    category: 'Place',
    image: 'assets/general/places/museum.png',
    lives: 'Usually found in cities',
    eats: 'Not applicable',
    description: 'A museum displays objects, art, and information about history and culture.',
  ),
  GeneralItem(
    name: 'Zoo (चिड़ियाघर)',
    category: 'Place',
    image: 'assets/general/places/zoo.png',
    lives: 'Found in many cities',
    eats: 'Not applicable',
    description: 'A zoo is a place where people can see many different animals.',
  ),
  GeneralItem(
    name: 'Airport (हवाई अड्डा)',
    category: 'Place',
    image: 'assets/general/places/airport.png',
    lives: 'Usually found near cities',
    eats: 'Not applicable',
    description: 'An airport is a place where aeroplanes take off and land.',
  ),
  GeneralItem(
    name: 'Railway Station (रेलवे स्टेशन)',
    category: 'Place',
    image: 'assets/general/places/railway_station.png',
    lives: 'Found in towns and cities',
    eats: 'Not applicable',
    description: 'A railway station is where passengers board and leave trains.',
  ),
  GeneralItem(
    name: 'Bus Station (बस स्टेशन)',
    category: 'Place',
    image: 'assets/general/places/bus_station.png',
    lives: 'Found in towns and cities',
    eats: 'Not applicable',
    description: 'A bus station is a place where buses pick up and drop off passengers.',
  ),
  GeneralItem(
    name: 'Police Station (पुलिस स्टेशन)',
    category: 'Place',
    image: 'assets/general/places/police_station.png',
    lives: 'Found in towns and cities',
    eats: 'Not applicable',
    description: 'A police station is a place where police officers work and help keep people safe.',
  ),
  GeneralItem(
    name: 'Fire Station (अग्निशमन केंद्र)',
    category: 'Place',
    image: 'assets/general/places/fire_station.png',
    lives: 'Found in towns and cities',
    eats: 'Not applicable',
    description: 'A fire station is where firefighters and fire engines are kept.',
  ),
  GeneralItem(
    name: 'Post Office (डाकघर)',
    category: 'Place',
    image: 'assets/general/places/post_office.png',
    lives: 'Found in towns and villages',
    eats: 'Not applicable',
    description: 'A post office provides services for sending letters and parcels.',
  ),
  GeneralItem(
    name: 'Bank (बैंक)',
    category: 'Place',
    image: 'assets/general/places/bank.png',
    lives: 'Found in towns and cities',
    eats: 'Not applicable',
    description: 'A bank is a place where people can save and manage money.',
  ),
  GeneralItem(
    name: 'Market (बाज़ार)',
    category: 'Place',
    image: 'assets/general/places/market.png',
    lives: 'Found in towns and villages',
    eats: 'Not applicable',
    description: 'A market is a place where people buy and sell different things.',
  ),
  GeneralItem(
    name: 'Supermarket (सुपरमार्केट)',
    category: 'Place',
    image: 'assets/general/places/supermarket.png',
    lives: 'Usually found in towns and cities',
    eats: 'Not applicable',
    description: 'A supermarket is a large store where people can buy many types of goods.',
  ),
  GeneralItem(
    name: 'Restaurant (रेस्तरां)',
    category: 'Place',
    image: 'assets/general/places/restaurant.png',
    lives: 'Found in towns and cities',
    eats: 'Not applicable',
    description: 'A restaurant is a place where people can buy and eat prepared food.',
  ),
  GeneralItem(
    name: 'Hotel (होटल)',
    category: 'Place',
    image: 'assets/general/places/hotel.png',
    lives: 'Found in towns and cities',
    eats: 'Not applicable',
    description: 'A hotel provides rooms and other services for people who are travelling.',
  ),
  GeneralItem(
    name: 'Temple (मंदिर)',
    category: 'Place',
    image: 'assets/general/places/temple.png',
    lives: 'Found in many communities',
    eats: 'Not applicable',
    description: 'A temple is a place where people go for prayer and worship.',
  ),
  GeneralItem(
    name: 'Mosque (मस्जिद)',
    category: 'Place',
    image: 'assets/general/places/mosque.png',
    lives: 'Found in many communities',
    eats: 'Not applicable',
    description: 'A mosque is a place where Muslims gather for prayer.',
  ),
  GeneralItem(
    name: 'Church (चर्च)',
    category: 'Place',
    image: 'assets/general/places/church.png',
    lives: 'Found in many communities',
    eats: 'Not applicable',
    description: 'A church is a place where Christians gather for worship.',
  ),
  GeneralItem(
    name: 'Beach (समुद्र तट)',
    category: 'Place',
    image: 'assets/general/places/beach.png',
    lives: 'Found along seas and oceans',
    eats: 'Not applicable',
    description: 'A beach is an area of sand or stones beside the sea or ocean.',
  ),
  GeneralItem(
    name: 'Mountain (पहाड़)',
    category: 'Place',
    image: 'assets/general/places/mountain.png',
    lives: 'Found in mountainous regions',
    eats: 'Not applicable',
    description: 'A mountain is a very high natural elevation of land.',
  ),
  GeneralItem(
    name: 'Forest (जंगल)',
    category: 'Place',
    image: 'assets/general/places/forest.png',
    lives: 'Found in many parts of the world',
    eats: 'Not applicable',
    description: 'A forest is a large area covered mainly with trees and other plants.',
  ),
  GeneralItem(
    name: 'Desert (रेगिस्तान)',
    category: 'Place',
    image: 'assets/general/places/desert.png',
    lives: 'Found in dry regions',
    eats: 'Not applicable',
    description: 'A desert is a very dry place that receives very little rainfall.',
  ),
  GeneralItem(
    name: 'River (नदी)',
    category: 'Place',
    image: 'assets/general/places/river.png',
    lives: 'Flows through many regions',
    eats: 'Not applicable',
    description: 'A river is a natural stream of flowing water.',
  ),
  GeneralItem(
    name: 'Lake (झील)',
    category: 'Place',
    image: 'assets/general/places/lake.png',
    lives: 'Found in lowlands and mountains',
    eats: 'Not applicable',
    description: 'A lake is a large body of water surrounded by land.',
  ),
  GeneralItem(
    name: 'Waterfall (झरना)',
    category: 'Place',
    image: 'assets/general/places/waterfall.png',
    lives: 'Often found in hilly and mountainous areas',
    eats: 'Not applicable',
    description: 'A waterfall is water flowing over a steep drop in a river or stream.',
  ),
  GeneralItem(
    name: 'Island (द्वीप)',
    category: 'Place',
    image: 'assets/general/places/island.png',
    lives: 'Found in oceans, seas, and lakes',
    eats: 'Not applicable',
    description: 'An island is a piece of land completely surrounded by water.',
  ),
  GeneralItem(
    name: 'Cave (गुफा)',
    category: 'Place',
    image: 'assets/general/places/cave.png',
    lives: 'Found mainly in rocky areas',
    eats: 'Not applicable',
    description: 'A cave is a natural hollow space inside the ground or a mountain.',
  ),
  GeneralItem(
    name: 'Farm (खेत)',
    category: 'Place',
    image: 'assets/general/places/farm.png',
    lives: 'Usually found in rural areas',
    eats: 'Not applicable',
    description: 'A farm is a place where crops are grown and animals may be raised.',
  ),
  GeneralItem(
    name: 'Garden (बगीचा)',
    category: 'Place',
    image: 'assets/general/places/garden.png',
    lives: 'Found near homes and public places',
    eats: 'Not applicable',
    description: 'A garden is an area where flowers, plants, and trees are grown.',
  ),
  GeneralItem(
    name: 'Playground (खेल का मैदान)',
    category: 'Place',
    image: 'assets/general/places/playground.png',
    lives: 'Found near schools and communities',
    eats: 'Not applicable',
    description: 'A playground is a place where children can play outdoor games.',
  ),
  GeneralItem(
    name: 'Stadium (स्टेडियम)',
    category: 'Place',
    image: 'assets/general/places/stadium.png',
    lives: 'Usually found in cities',
    eats: 'Not applicable',
    description: 'A stadium is a large place where sports matches and events are held.',
  ),
  GeneralItem(
    name: 'Theatre (रंगमंच)',
    category: 'Place',
    image: 'assets/general/places/theatre.png',
    lives: 'Usually found in towns and cities',
    eats: 'Not applicable',
    description: 'A theatre is a place where people watch plays, performances, and shows.',
  ),
  GeneralItem(
    name: 'Cinema Hall (सिनेमा हॉल)',
    category: 'Place',
    image: 'assets/general/places/cinema.png',
    lives: 'Found mainly in towns and cities',
    eats: 'Not applicable',
    description: 'A cinema hall is a place where people watch movies on a large screen.',
  ),
  GeneralItem(
    name: 'Shopping Mall (शॉपिंग मॉल)',
    category: 'Place',
    image: 'assets/general/places/mall.png',
    lives: 'Usually found in cities',
    eats: 'Not applicable',
    description: 'A shopping mall has many shops, restaurants, and entertainment areas.',
  ),
  GeneralItem(
    name: 'Harbour (बंदरगाह)',
    category: 'Place',
    image: 'assets/general/places/harbour.png',
    lives: 'Found along seas and oceans',
    eats: 'Not applicable',
    description: 'A harbour is a sheltered place where ships and boats can stop.',
  ),
  GeneralItem(
    name: 'Port (बंदरगाह)',
    category: 'Place',
    image: 'assets/general/places/port.png',
    lives: 'Found near seas and rivers',
    eats: 'Not applicable',
    description: 'A port is a place where ships load and unload people and goods.',
  ),
  GeneralItem(
    name: 'Bridge (पुल)',
    category: 'Place',
    image: 'assets/general/places/bridge.png',
    lives: 'Built over rivers, roads, and valleys',
    eats: 'Not applicable',
    description: 'A bridge helps people and vehicles cross an obstacle such as a river or road.',
  ),
  GeneralItem(
    name: 'Tunnel (सुरंग)',
    category: 'Place',
    image: 'assets/general/places/tunnel.png',
    lives: 'Built through mountains or underground',
    eats: 'Not applicable',
    description: 'A tunnel is a passage built through or under the ground.',
  ),
  GeneralItem(
    name: 'Village (गाँव)',
    category: 'Place',
    image: 'assets/general/places/village.png',
    lives: 'Usually found in rural areas',
    eats: 'Not applicable',
    description: 'A village is a small community where people often live close to farms and nature.',
  ),
  GeneralItem(
    name: 'City (शहर)',
    category: 'Place',
    image: 'assets/general/places/city.png',
    lives: 'Found across countries',
    eats: 'Not applicable',
    description: 'A city is a large populated area with homes, offices, schools, and businesses.',
  ),
  GeneralItem(
    name: 'Capital City (राजधानी)',
    category: 'Place',
    image: 'assets/general/places/capital_city.png',
    lives: 'Found in every country or state with a designated capital',
    eats: 'Not applicable',
    description: 'A capital city is an important city where a government has its main offices.',
  ),
  GeneralItem(
    name: 'Palace (महल)',
    category: 'Place',
    image: 'assets/general/places/palace.png',
    lives: 'Found in many historical regions',
    eats: 'Not applicable',
    description: 'A palace is a large and grand building often connected with kings or rulers.',
  ),
  GeneralItem(
    name: 'Fort (किला)',
    category: 'Place',
    image: 'assets/general/places/fort.png',
    lives: 'Often found in historical regions',
    eats: 'Not applicable',
    description: 'A fort is a strong building or group of buildings made for protection.',
  ),
  GeneralItem(
    name: 'Monument (स्मारक)',
    category: 'Place',
    image: 'assets/general/places/monument.png',
    lives: 'Found in cities and historical places',
    eats: 'Not applicable',
    description: 'A monument is built to remember an important person, event, or part of history.',
  ),
  GeneralItem(
    name: 'Historical Site (ऐतिहासिक स्थल)',
    category: 'Place',
    image: 'assets/general/places/historical_site.png',
    lives: 'Found in places with important history',
    eats: 'Not applicable',
    description: 'A historical site is a place connected with important events or people from the past.',
  ),
  GeneralItem(
    name: 'National Park (राष्ट्रीय उद्यान)',
    category: 'Place',
    image: 'assets/general/places/national_park.png',
    lives: 'Found in protected natural areas',
    eats: 'Not applicable',
    description: 'A national park protects plants, animals, and natural environments.',
  ),
  GeneralItem(
    name: 'Wildlife Sanctuary (वन्यजीव अभयारण्य)',
    category: 'Place',
    image: 'assets/general/places/wildlife_sanctuary.png',
    lives: 'Found in protected natural areas',
    eats: 'Not applicable',
    description: 'A wildlife sanctuary is a protected area where wild animals can live safely.',
  ),
  GeneralItem(
    name: 'Botanical Garden (वनस्पति उद्यान)',
    category: 'Place',
    image: 'assets/general/places/botanical_garden.png',
    lives: 'Found in many cities and educational areas',
    eats: 'Not applicable',
    description: 'A botanical garden is a place where many different kinds of plants are grown and studied.',
  ),
  GeneralItem(
    name: 'Aquarium (मछलीघर)',
    category: 'Place',
    image: 'assets/general/places/aquarium.png',
    lives: 'Usually found in cities and tourist places',
    eats: 'Not applicable',
    description: 'An aquarium is a place where people can see fish and other aquatic animals.',
  ),
  GeneralItem(
    name: 'Science Centre (विज्ञान केंद्र)',
    category: 'Place',
    image: 'assets/general/places/science_centre.png',
    lives: 'Usually found in cities',
    eats: 'Not applicable',
    description: 'A science centre is a place where children and adults can learn science through exhibits and activities.',
  ),
  GeneralItem(
    name: 'Bus Stop (बस स्टॉप)',
    category: 'Place',
    image: 'assets/general/places/bus_stop.png',
    lives: 'Found along roads in towns and cities',
    eats: 'Not applicable',
    description: 'A bus stop is a place where people wait for buses.',
  ),
  GeneralItem(
    name: 'Petrol Pump (पेट्रोल पंप)',
    category: 'Place',
    image: 'assets/general/places/petrol_pump.png',
    lives: 'Found along roads and in cities',
    eats: 'Not applicable',
    description: 'A petrol pump is a place where vehicles can get fuel.',
  ),
];