import 'general_data.dart';

final List<GeneralItem> plantsAndTrees = [
  GeneralItem(
    name: 'Mango Tree (आम का पेड़)',
    category: 'Tree',
    image: 'assets/general/plants_trees/mango_tree.png',
    lives: 'Grows in warm and tropical regions',
    eats: 'Not applicable',
    description: 'Mango trees are large trees that produce sweet mango fruits.',
  ),
  GeneralItem(
    name: 'Neem Tree (नीम का पेड़)',
    category: 'Tree',
    image: 'assets/general/plants_trees/neem_tree.png',
    lives: 'Grows in warm and dry regions',
    eats: 'Not applicable',
    description: 'Neem is a useful tree known for its bitter leaves and medicinal properties.',
  ),
  GeneralItem(
    name: 'Banyan Tree (बरगद का पेड़)',
    category: 'Tree',
    image: 'assets/general/plants_trees/banyan_tree.png',
    lives: 'Grows in warm regions',
    eats: 'Not applicable',
    description: 'The banyan tree has large branches and hanging roots that reach the ground.',
  ),
  GeneralItem(
    name: 'Peepal Tree (पीपल का पेड़)',
    category: 'Tree',
    image: 'assets/general/plants_trees/peepal_tree.png',
    lives: 'Grows in warm regions',
    eats: 'Not applicable',
    description: 'Peepal trees have heart-shaped leaves with long tips.',
  ),
  GeneralItem(
    name: 'Coconut Tree (नारियल का पेड़)',
    category: 'Tree',
    image: 'assets/general/plants_trees/coconut_tree.png',
    lives: 'Grows mainly in tropical coastal areas',
    eats: 'Not applicable',
    description: 'Coconut palms produce coconuts and have long feather-like leaves.',
  ),
  GeneralItem(
    name: 'Palm Tree (ताड़ का पेड़)',
    category: 'Tree',
    image: 'assets/general/plants_trees/palm_tree.png',
    lives: 'Grows in warm climates',
    eats: 'Not applicable',
    description: 'Palm trees have tall trunks and large leaves at the top.',
  ),
  GeneralItem(
    name: 'Bamboo (बांस)',
    category: 'Plant',
    image: 'assets/general/plants_trees/bamboo.png',
    lives: 'Grows in forests and warm regions',
    eats: 'Not applicable',
    description: 'Bamboo is a fast-growing plant with tall, hollow stems.',
  ),
  GeneralItem(
    name: 'Tulsi (तुलसी)',
    category: 'Plant',
    image: 'assets/general/plants_trees/tulsi.png',
    lives: 'Grows well in warm and sunny places',
    eats: 'Not applicable',
    description: 'Tulsi is a small aromatic plant commonly grown in Indian homes.',
  ),
  GeneralItem(
    name: 'Aloe Vera (एलोवेरा)',
    category: 'Plant',
    image: 'assets/general/plants_trees/aloe_vera.png',
    lives: 'Grows in warm and dry places',
    eats: 'Not applicable',
    description: 'Aloe vera has thick, fleshy leaves that store water.',
  ),
  GeneralItem(
    name: 'Money Plant (मनी प्लांट)',
    category: 'Plant',
    image: 'assets/general/plants_trees/money_plant.png',
    lives: 'Grows indoors and outdoors',
    eats: 'Not applicable',
    description: 'Money plants are climbing plants with attractive heart-shaped leaves.',
  ),
  GeneralItem(
    name: 'Rose Plant (गुलाब का पौधा)',
    category: 'Plant',
    image: 'assets/general/plants_trees/rose_plant.png',
    lives: 'Grows in gardens and sunny places',
    eats: 'Not applicable',
    description: 'Rose plants produce beautiful flowers and often have thorns.',
  ),
  GeneralItem(
    name: 'Hibiscus Plant (गुड़हल का पौधा)',
    category: 'Plant',
    image: 'assets/general/plants_trees/hibiscus_plant.png',
    lives: 'Grows in warm and sunny places',
    eats: 'Not applicable',
    description: 'Hibiscus plants produce large, colourful flowers.',
  ),
  GeneralItem(
    name: 'Jasmine Plant (चमेली का पौधा)',
    category: 'Plant',
    image: 'assets/general/plants_trees/jasmine_plant.png',
    lives: 'Grows in warm climates',
    eats: 'Not applicable',
    description: 'Jasmine is known for its small white flowers and sweet fragrance.',
  ),
  GeneralItem(
    name: 'Sunflower Plant (सूरजमुखी का पौधा)',
    category: 'Plant',
    image: 'assets/general/plants_trees/sunflower_plant.png',
    lives: 'Grows best in sunny places',
    eats: 'Not applicable',
    description: 'Sunflower plants produce large yellow flowers that turn toward sunlight.',
  ),
  GeneralItem(
    name: 'Money Plant (मनी प्लांट)',
    category: 'Plant',
    image: 'assets/general/plants_trees/money_plant.png',
    lives: 'Grows in homes and gardens',
    eats: 'Not applicable',
    description: 'Money plant is a popular decorative climbing plant.',
  ),
  GeneralItem(
    name: 'Guava Tree (अमरूद का पेड़)',
    category: 'Tree',
    image: 'assets/general/plants_trees/guava_tree.png',
    lives: 'Grows in warm tropical regions',
    eats: 'Not applicable',
    description: 'Guava trees produce round or oval fruits with edible seeds.',
  ),
  GeneralItem(
    name: 'Apple Tree (सेब का पेड़)',
    category: 'Tree',
    image: 'assets/general/plants_trees/apple_tree.png',
    lives: 'Grows mainly in cool and temperate regions',
    eats: 'Not applicable',
    description: 'Apple trees produce crisp and juicy apples.',
  ),
  GeneralItem(
    name: 'Banana Plant (केले का पौधा)',
    category: 'Plant',
    image: 'assets/general/plants_trees/banana_plant.png',
    lives: 'Grows in warm and humid regions',
    eats: 'Not applicable',
    description: 'The banana plant has large leaves and produces bunches of bananas.',
  ),
  GeneralItem(
    name: 'Papaya Plant (पपीते का पौधा)',
    category: 'Plant',
    image: 'assets/general/plants_trees/papaya_plant.png',
    lives: 'Grows in warm tropical regions',
    eats: 'Not applicable',
    description: 'Papaya plants have large leaves and produce soft orange fruits.',
  ),
  GeneralItem(
    name: 'Lemon Tree (नींबू का पेड़)',
    category: 'Tree',
    image: 'assets/general/plants_trees/lemon_tree.png',
    lives: 'Grows in warm and sunny regions',
    eats: 'Not applicable',
    description: 'Lemon trees produce small yellow fruits with a sour taste.',
  ),
  GeneralItem(
    name: 'Orange Tree (संतरे का पेड़)',
    category: 'Tree',
    image: 'assets/general/plants_trees/orange_tree.png',
    lives: 'Grows in warm climates',
    eats: 'Not applicable',
    description: 'Orange trees produce juicy orange-coloured citrus fruits.',
  ),
  GeneralItem(
    name: 'Guava Plant (अमरूद का पौधा)',
    category: 'Plant',
    image: 'assets/general/plants_trees/guava_plant.png',
    lives: 'Grows in warm climates',
    eats: 'Not applicable',
    description: 'Young guava plants grow into small trees that produce guavas.',
  ),
  GeneralItem(
    name: 'Ashoka Tree (अशोक का पेड़)',
    category: 'Tree',
    image: 'assets/general/plants_trees/ashoka_tree.png',
    lives: 'Grows in warm and tropical regions',
    eats: 'Not applicable',
    description: 'Ashoka trees are often planted for their attractive leaves and flowers.',
  ),
  GeneralItem(
    name: 'Gulmohar Tree (गुलमोहर का पेड़)',
    category: 'Tree',
    image: 'assets/general/plants_trees/gulmohar_tree.png',
    lives: 'Grows in warm regions',
    eats: 'Not applicable',
    description: 'Gulmohar trees are famous for their bright red and orange flowers.',
  ),
  GeneralItem(
    name: 'Teak Tree (सागौन का पेड़)',
    category: 'Tree',
    image: 'assets/general/plants_trees/teak_tree.png',
    lives: 'Grows in tropical forests',
    eats: 'Not applicable',
    description: 'Teak trees are large trees valued for their strong wood.',
  ),
  GeneralItem(
    name: 'Sal Tree (साल का पेड़)',
    category: 'Tree',
    image: 'assets/general/plants_trees/sal_tree.png',
    lives: 'Grows in forests of South Asia',
    eats: 'Not applicable',
    description: 'Sal trees are tall forest trees with strong wood.',
  ),
  GeneralItem(
    name: 'Eucalyptus Tree (नीलगिरी का पेड़)',
    category: 'Tree',
    image: 'assets/general/plants_trees/eucalyptus_tree.png',
    lives: 'Grows in warm and temperate regions',
    eats: 'Not applicable',
    description: 'Eucalyptus trees have aromatic leaves and tall trunks.',
  ),
  GeneralItem(
    name: 'Pine Tree (चीड़ का पेड़)',
    category: 'Tree',
    image: 'assets/general/plants_trees/pine_tree.png',
    lives: 'Grows in cool and mountainous regions',
    eats: 'Not applicable',
    description: 'Pine trees have needle-like leaves and produce cones.',
  ),
  GeneralItem(
    name: 'Fir Tree (देवदार जैसा फर का पेड़)',
    category: 'Tree',
    image: 'assets/general/plants_trees/fir_tree.png',
    lives: 'Grows mainly in cool mountainous regions',
    eats: 'Not applicable',
    description: 'Fir trees are evergreen trees with cone-shaped forms.',
  ),
  GeneralItem(
    name: 'Deodar Tree (देवदार का पेड़)',
    category: 'Tree',
    image: 'assets/general/plants_trees/deodar_tree.png',
    lives: 'Grows in Himalayan mountains',
    eats: 'Not applicable',
    description: 'Deodar is a tall evergreen tree found in Himalayan regions.',
  ),
  GeneralItem(
    name: 'Bamboo Plant (बांस का पौधा)',
    category: 'Plant',
    image: 'assets/general/plants_trees/bamboo_plant.png',
    lives: 'Grows in forests and tropical regions',
    eats: 'Not applicable',
    description: 'Bamboo grows in groups and can reach great heights.',
  ),
  GeneralItem(
    name: 'Cactus (कैक्टस)',
    category: 'Plant',
    image: 'assets/general/plants_trees/cactus.png',
    lives: 'Grows in deserts and dry regions',
    eats: 'Not applicable',
    description: 'Cactus plants store water in their thick stems and need little water.',
  ),
  GeneralItem(
    name: 'Money Plant Vine (मनी प्लांट की बेल)',
    category: 'Plant',
    image: 'assets/general/plants_trees/money_vine.png',
    lives: 'Grows on supports and in pots',
    eats: 'Not applicable',
    description: 'This climbing plant can grow long vines with heart-shaped leaves.',
  ),
  GeneralItem(
    name: 'Mint Plant (पुदीने का पौधा)',
    category: 'Plant',
    image: 'assets/general/plants_trees/mint.png',
    lives: 'Grows in moist soil',
    eats: 'Not applicable',
    description: 'Mint is a small aromatic herb with fresh-smelling leaves.',
  ),
  GeneralItem(
    name: 'Coriander Plant (धनिया का पौधा)',
    category: 'Plant',
    image: 'assets/general/plants_trees/coriander.png',
    lives: 'Grows in gardens and pots',
    eats: 'Not applicable',
    description: 'Coriander is a herb whose fresh leaves are commonly used in food.',
  ),
  GeneralItem(
    name: 'Basil Plant (तुलसी जैसा बेसिल पौधा)',
    category: 'Plant',
    image: 'assets/general/plants_trees/basil.png',
    lives: 'Grows in warm and sunny places',
    eats: 'Not applicable',
    description: 'Basil is an aromatic herb with soft green leaves.',
  ),
  GeneralItem(
    name: 'Curry Leaf Plant (करी पत्ता का पौधा)',
    category: 'Plant',
    image: 'assets/general/plants_trees/curry_leaf.png',
    lives: 'Grows in warm climates',
    eats: 'Not applicable',
    description: 'Curry leaf plants provide fragrant leaves commonly used in Indian cooking.',
  ),
  GeneralItem(
    name: 'Tomato Plant (टमाटर का पौधा)',
    category: 'Plant',
    image: 'assets/general/plants_trees/tomato_plant.png',
    lives: 'Grows in sunny gardens and farms',
    eats: 'Not applicable',
    description: 'Tomato plants produce round fruits that can be red, yellow, or orange.',
  ),
  GeneralItem(
    name: 'Chilli Plant (मिर्च का पौधा)',
    category: 'Plant',
    image: 'assets/general/plants_trees/chilli_plant.png',
    lives: 'Grows in warm and sunny places',
    eats: 'Not applicable',
    description: 'Chilli plants produce small fruits that can have a spicy taste.',
  ),
  GeneralItem(
    name: 'Potato Plant (आलू का पौधा)',
    category: 'Plant',
    image: 'assets/general/plants_trees/potato_plant.png',
    lives: 'Grows in soil on farms',
    eats: 'Not applicable',
    description: 'Potato plants grow underground tubers that we use as food.',
  ),
  GeneralItem(
    name: 'Pea Plant (मटर का पौधा)',
    category: 'Plant',
    image: 'assets/general/plants_trees/pea_plant.png',
    lives: 'Grows in cool seasons',
    eats: 'Not applicable',
    description: 'Pea plants produce green pods containing small round peas.',
  ),
  GeneralItem(
    name: 'Banyan Sapling (बरगद का पौधा)',
    category: 'Plant',
    image: 'assets/general/plants_trees/banyan_sapling.png',
    lives: 'Grows in warm regions',
    eats: 'Not applicable',
    description: 'A banyan sapling is a young banyan tree that grows into a large tree.',
  ),
  GeneralItem(
    name: 'Neem Sapling (नीम का पौधा)',
    category: 'Plant',
    image: 'assets/general/plants_trees/neem_sapling.png',
    lives: 'Grows in warm and sunny regions',
    eats: 'Not applicable',
    description: 'A neem sapling is a young neem tree with small green leaves.',
  ),
  GeneralItem(
    name: 'Christmas Tree (क्रिसमस ट्री)',
    category: 'Tree',
    image: 'assets/general/plants_trees/christmas_tree.png',
    lives: 'Grows mainly in cool regions',
    eats: 'Not applicable',
    description: 'Evergreen trees such as fir and pine are commonly used as Christmas trees.',
  ),
  GeneralItem(
    name: 'Willow Tree (विलो का पेड़)',
    category: 'Tree',
    image: 'assets/general/plants_trees/willow_tree.png',
    lives: 'Grows well near water',
    eats: 'Not applicable',
    description: 'Willow trees often have long, narrow leaves and flexible branches.',
  ),
  GeneralItem(
    name: 'Oak Tree (बलूत का पेड़)',
    category: 'Tree',
    image: 'assets/general/plants_trees/oak_tree.png',
    lives: 'Grows in temperate regions',
    eats: 'Not applicable',
    description: 'Oak trees are strong trees that produce acorns.',
  ),
  GeneralItem(
    name: 'Maple Tree (मेपल का पेड़)',
    category: 'Tree',
    image: 'assets/general/plants_trees/maple_tree.png',
    lives: 'Grows in temperate regions',
    eats: 'Not applicable',
    description: 'Maple trees have distinctive leaves and produce winged seeds.',
  ),
  GeneralItem(
    name: 'Bamboo Palm (बांस पाम)',
    category: 'Plant',
    image: 'assets/general/plants_trees/bamboo_palm.png',
    lives: 'Grows in warm and shaded places',
    eats: 'Not applicable',
    description: 'Bamboo palm is a decorative palm plant often grown indoors.',
  ),
  GeneralItem(
    name: 'Fern (फर्न)',
    category: 'Plant',
    image: 'assets/general/plants_trees/fern.png',
    lives: 'Grows in moist and shady places',
    eats: 'Not applicable',
    description: 'Ferns have beautiful green leaves called fronds and do not produce flowers.',
  ),
  GeneralItem(
    name: 'Moneywort (मनीवर्ट)',
    category: 'Plant',
    image: 'assets/general/plants_trees/moneywort.png',
    lives: 'Grows in moist soil',
    eats: 'Not applicable',
    description: 'Moneywort is a small green plant often used as ground cover.',
  ),
  GeneralItem(
    name: 'Lotus Plant (कमल का पौधा)',
    category: 'Plant',
    image: 'assets/general/plants_trees/lotus_plant.png',
    lives: 'Grows in ponds and still water',
    eats: 'Not applicable',
    description: 'Lotus plants have large round leaves and beautiful flowers that float above water.',
  ),
  GeneralItem(
    name: 'Water Lily (कुमुदिनी)',
    category: 'Plant',
    image: 'assets/general/plants_trees/water_lily.png',
    lives: 'Grows in ponds and freshwater',
    eats: 'Not applicable',
    description: 'Water lilies have floating leaves and colourful flowers.',
  ),
];