import 'general_data.dart';

final List<GeneralItem> sportsAndGames = [
  GeneralItem(
    name: 'Cricket (क्रिकेट)',
    category: 'Sport',
    image: 'assets/general/sports_games/cricket.png',
    lives: '',
    eats: '',
    description: 'Cricket is a team sport played with a bat and ball. Players score runs by hitting the ball.',
  ),
  GeneralItem(
    name: 'Football (फुटबॉल)',
    category: 'Sport',
    image: 'assets/general/sports_games/football.png',
    lives: '',
    eats: '',
    description: 'Football is played between two teams that try to score goals by kicking the ball.',
  ),
  GeneralItem(
    name: 'Basketball (बास्केटबॉल)',
    category: 'Sport',
    image: 'assets/general/sports_games/basketball.png',
    lives: '',
    eats: '',
    description: 'Basketball is played by two teams that try to put the ball through a hoop.',
  ),
  GeneralItem(
    name: 'Tennis (टेनिस)',
    category: 'Sport',
    image: 'assets/general/sports_games/tennis.png',
    lives: '',
    eats: '',
    description: 'Tennis is played with a racket and ball across a net.',
  ),
  GeneralItem(
    name: 'Badminton (बैडमिंटन)',
    category: 'Sport',
    image: 'assets/general/sports_games/badminton.png',
    lives: '',
    eats: '',
    description: 'Badminton is played with rackets and a shuttlecock across a net.',
  ),
  GeneralItem(
    name: 'Table Tennis (टेबल टेनिस)',
    category: 'Sport',
    image: 'assets/general/sports_games/table_tennis.png',
    lives: '',
    eats: '',
    description: 'Table tennis is played on a table using small rackets and a lightweight ball.',
  ),
  GeneralItem(
    name: 'Hockey (हॉकी)',
    category: 'Sport',
    image: 'assets/general/sports_games/hockey.png',
    lives: '',
    eats: '',
    description: 'Hockey is played with sticks and a ball or puck, depending on the type of hockey.',
  ),
  GeneralItem(
    name: 'Volleyball (वॉलीबॉल)',
    category: 'Sport',
    image: 'assets/general/sports_games/volleyball.png',
    lives: '',
    eats: '',
    description: 'Volleyball is played by teams who hit a ball over a net.',
  ),
  GeneralItem(
    name: 'Baseball (बेसबॉल)',
    category: 'Sport',
    image: 'assets/general/sports_games/baseball.png',
    lives: '',
    eats: '',
    description: 'Baseball is a bat-and-ball sport in which players score by running around bases.',
  ),
  GeneralItem(
    name: 'Golf (गोल्फ)',
    category: 'Sport',
    image: 'assets/general/sports_games/golf.png',
    lives: '',
    eats: '',
    description: 'Golf is played by hitting a small ball into holes using as few strokes as possible.',
  ),
  GeneralItem(
    name: 'Boxing (मुक्केबाज़ी)',
    category: 'Sport',
    image: 'assets/general/sports_games/boxing.png',
    lives: '',
    eats: '',
    description: 'Boxing is a combat sport in which two competitors use their fists while following rules.',
  ),
  GeneralItem(
    name: 'Wrestling (कुश्ती)',
    category: 'Sport',
    image: 'assets/general/sports_games/wrestling.png',
    lives: '',
    eats: '',
    description: 'Wrestling is a sport in which competitors use controlled holds and techniques.',
  ),
  GeneralItem(
    name: 'Swimming (तैराकी)',
    category: 'Sport',
    image: 'assets/general/sports_games/swimming.png',
    lives: '',
    eats: '',
    description: 'Swimming is a sport in which people move through water using different strokes.',
  ),
  GeneralItem(
    name: 'Running (दौड़)',
    category: 'Sport',
    image: 'assets/general/sports_games/running.png',
    lives: '',
    eats: '',
    description: 'Running is an athletic activity in which a person moves quickly using their legs.',
  ),
  GeneralItem(
    name: 'Cycling (साइकिल चलाना)',
    category: 'Sport',
    image: 'assets/general/sports_games/cycling.png',
    lives: '',
    eats: '',
    description: 'Cycling is a sport and activity performed by riding a bicycle.',
  ),
  GeneralItem(
    name: 'Archery (तीरंदाजी)',
    category: 'Sport',
    image: 'assets/general/sports_games/archery.png',
    lives: '',
    eats: '',
    description: 'Archery is a sport in which players use a bow to shoot arrows at a target.',
  ),
  GeneralItem(
    name: 'Gymnastics (जिम्नास्टिक)',
    category: 'Sport',
    image: 'assets/general/sports_games/gymnastics.png',
    lives: '',
    eats: '',
    description: 'Gymnastics involves strength, balance, flexibility, and controlled body movements.',
  ),
  GeneralItem(
    name: 'Karate (कराटे)',
    category: 'Sport',
    image: 'assets/general/sports_games/karate.png',
    lives: '',
    eats: '',
    description: 'Karate is a martial art that teaches controlled movements, discipline, and self-defence.',
  ),
  GeneralItem(
    name: 'Judo (जूडो)',
    category: 'Sport',
    image: 'assets/general/sports_games/judo.png',
    lives: '',
    eats: '',
    description: 'Judo is a martial art and sport that focuses on throws and controlled techniques.',
  ),
  GeneralItem(
    name: 'Taekwondo (ताइक्वांडो)',
    category: 'Sport',
    image: 'assets/general/sports_games/taekwondo.png',
    lives: '',
    eats: '',
    description: 'Taekwondo is a martial art known especially for its kicking techniques.',
  ),
  GeneralItem(
    name: 'Skating (स्केटिंग)',
    category: 'Sport',
    image: 'assets/general/sports_games/skating.png',
    lives: '',
    eats: '',
    description: 'Skating involves moving across a surface using skates.',
  ),
  GeneralItem(
    name: 'Ice Hockey (आइस हॉकी)',
    category: 'Sport',
    image: 'assets/general/sports_games/ice_hockey.png',
    lives: '',
    eats: '',
    description: 'Ice hockey is played on ice using sticks and a puck.',
  ),
  GeneralItem(
    name: 'Chess (शतरंज)',
    category: 'Game',
    image: 'assets/general/sports_games/chess.png',
    lives: '',
    eats: '',
    description: 'Chess is a strategy board game played between two players.',
  ),
  GeneralItem(
    name: 'Carrom (कैरम)',
    category: 'Game',
    image: 'assets/general/sports_games/carrom.png',
    lives: '',
    eats: '',
    description: 'Carrom is a tabletop game in which players use a striker to hit pieces into pockets.',
  ),
  GeneralItem(
    name: 'Ludo (लूडो)',
    category: 'Game',
    image: 'assets/general/sports_games/ludo.png',
    lives: '',
    eats: '',
    description: 'Ludo is a board game where players move tokens according to dice rolls.',
  ),
  GeneralItem(
    name: 'Snakes and Ladders (सांप और सीढ़ी)',
    category: 'Game',
    image: 'assets/general/sports_games/snakes_ladders.png',
    lives: '',
    eats: '',
    description: 'Players move across a numbered board using dice, climbing ladders and avoiding snakes.',
  ),
  GeneralItem(
    name: 'Hide and Seek (छुपन-छुपाई)',
    category: 'Game',
    image: 'assets/general/sports_games/hide_and_seek.png',
    lives: '',
    eats: '',
    description: 'One player searches while the other players hide.',
  ),
  GeneralItem(
    name: 'Tag (पकड़म-पकड़ाई)',
    category: 'Game',
    image: 'assets/general/sports_games/tag.png',
    lives: '',
    eats: '',
    description: 'In tag, one player tries to touch or tag another player.',
  ),
  GeneralItem(
    name: 'Hopscotch (पिट्ठू/स्टापू)',
    category: 'Game',
    image: 'assets/general/sports_games/hopscotch.png',
    lives: '',
    eats: '',
    description: 'Hopscotch is a playground game where players hop through numbered squares.',
  ),
  GeneralItem(
    name: 'Skipping (रस्सी कूद)',
    category: 'Game',
    image: 'assets/general/sports_games/skipping.png',
    lives: '',
    eats: '',
    description: 'Skipping involves jumping over a rope as it passes under the feet.',
  ),
  GeneralItem(
    name: 'Kabaddi (कबड्डी)',
    category: 'Sport',
    image: 'assets/general/sports_games/kabaddi.png',
    lives: '',
    eats: '',
    description: 'Kabaddi is a team sport where players try to tag opponents while following special rules.',
  ),
  GeneralItem(
    name: 'Kho Kho (खो-खो)',
    category: 'Sport',
    image: 'assets/general/sports_games/kho_kho.png',
    lives: '',
    eats: '',
    description: 'Kho Kho is a traditional Indian team sport involving chasing and defending.',
  ),
  GeneralItem(
    name: 'Table Soccer (टेबल सॉकर)',
    category: 'Game',
    image: 'assets/general/sports_games/table_soccer.png',
    lives: '',
    eats: '',
    description: 'Table soccer is a game where players control small figures to move a ball and score goals.',
  ),
  GeneralItem(
    name: 'Darts (डार्ट्स)',
    category: 'Game',
    image: 'assets/general/sports_games/darts.png',
    lives: '',
    eats: '',
    description: 'Darts is a target game in which players throw darts at a circular board.',
  ),
  GeneralItem(
    name: 'Bowling (बॉलिंग)',
    category: 'Sport',
    image: 'assets/general/sports_games/bowling.png',
    lives: '',
    eats: '',
    description: 'Bowling involves rolling a ball toward pins to knock down as many as possible.',
  ),
  GeneralItem(
    name: 'Skateboarding (स्केटबोर्डिंग)',
    category: 'Sport',
    image: 'assets/general/sports_games/skateboarding.png',
    lives: '',
    eats: '',
    description: 'Skateboarding is performed by riding and balancing on a skateboard.',
  ),
  GeneralItem(
    name: 'Surfing (सर्फिंग)',
    category: 'Sport',
    image: 'assets/general/sports_games/surfing.png',
    lives: '',
    eats: '',
    description: 'Surfing involves riding waves on a board.',
  ),
  GeneralItem(
    name: 'Rowing (नौका दौड़)',
    category: 'Sport',
    image: 'assets/general/sports_games/rowing.png',
    lives: '',
    eats: '',
    description: 'Rowing is a water sport in which people move a boat using oars.',
  ),
  GeneralItem(
    name: 'Sailing (नौकायन)',
    category: 'Sport',
    image: 'assets/general/sports_games/sailing.png',
    lives: '',
    eats: '',
    description: 'Sailing involves moving a boat using wind and sails.',
  ),
  GeneralItem(
    name: 'Horse Riding (घुड़सवारी)',
    category: 'Sport',
    image: 'assets/general/sports_games/horse_riding.png',
    lives: '',
    eats: '',
    description: 'Horse riding is the sport or activity of riding a horse.',
  ),
  GeneralItem(
    name: 'Polo (पोलो)',
    category: 'Sport',
    image: 'assets/general/sports_games/polo.png',
    lives: '',
    eats: '',
    description: 'Polo is played on horseback using long-handled sticks to hit a ball.',
  ),
  GeneralItem(
    name: 'Fencing (तलवारबाज़ी)',
    category: 'Sport',
    image: 'assets/general/sports_games/fencing.png',
    lives: '',
    eats: '',
    description: 'Fencing is a sport in which competitors use special swords while following safety rules.',
  ),
  GeneralItem(
    name: 'Weightlifting (भारोत्तोलन)',
    category: 'Sport',
    image: 'assets/general/sports_games/weightlifting.png',
    lives: '',
    eats: '',
    description: 'Weightlifting is a sport where athletes lift heavy weights using controlled techniques.',
  ),
  GeneralItem(
    name: 'Long Jump (लंबी कूद)',
    category: 'Sport',
    image: 'assets/general/sports_games/long_jump.png',
    lives: '',
    eats: '',
    description: 'Long jump is an athletic event where competitors run and jump as far as possible.',
  ),
  GeneralItem(
    name: 'High Jump (ऊंची कूद)',
    category: 'Sport',
    image: 'assets/general/sports_games/high_jump.png',
    lives: '',
    eats: '',
    description: 'High jump is an athletic event where competitors try to jump over a raised bar.',
  ),
  GeneralItem(
    name: 'Javelin Throw (भाला फेंक)',
    category: 'Sport',
    image: 'assets/general/sports_games/javelin.png',
    lives: '',
    eats: '',
    description: 'Javelin throw is an athletics event where competitors throw a long spear-like object for distance.',
  ),
  GeneralItem(
    name: 'Shot Put (गोला फेंक)',
    category: 'Sport',
    image: 'assets/general/sports_games/shot_put.png',
    lives: '',
    eats: '',
    description: 'Shot put is an athletics event where an athlete pushes a heavy metal ball for distance.',
  ),
  GeneralItem(
    name: 'Relay Race (रिले दौड़)',
    category: 'Sport',
    image: 'assets/general/sports_games/relay_race.png',
    lives: '',
    eats: '',
    description: 'A relay race is a team race where runners take turns and pass a baton.',
  ),
  GeneralItem(
    name: 'Marathon (मैराथन)',
    category: 'Sport',
    image: 'assets/general/sports_games/marathon.png',
    lives: '',
    eats: '',
    description: 'A marathon is a long-distance running race.',
  ),
];